pkg/source/curve/constant.go
pkg/source/curve/pool_aave.go
pkg/source/curve/pool_base.go
pkg/source/curve/pool_compound.go

we're using underlying tokens for aave/compound curve pools, so should use underlying decimals instead of normal decimals

use get_underlying_decimals for curve aave/compound

---

pkg/source/curve/constant.go
pkg/source/curve/pool_aave.go
pkg/source/curve/pool_base.go
pkg/source/curve/pool_compound.go
pkg/source/curve/pool_lists_classifier.go
pkg/source/curve/pool_meta.go
pkg/source/curve/pool_plain_oracle.go
pkg/source/curve/pool_tricrypto.go
pkg/source/curve/pool_two.go
pkg/source/curve/pools_list_updater.go
pkg/source/curve/type.go

- Change `*abi.ABI` and `*string` to `abi.ABI` and `string` to avoid weird issue wrong ABI file => `get_underlying_coins not found`
- Stop using `logger.WithFields` because it logs incorrect position of code
- In case of Optimism, the `meta pools factory` address is equal to the `crypto pools factory` address
- We should only process Curve Two and Curve Tricrypto for `crypto pools registry` and `crypto pools factory`
- Thus, now I added `poolsSourceIndex`. 
- 1 = `main registry`, 2 = `meta pools factory`, 3 = `crypto pools registry`, 4 = `crypto pools factory`
- Only 3 and 4 should be applied for Curve Two and Curve Tricrypto

fix: curve incorrect pool classify

---

pkg/source/handler.go
pkg/source/lido-steth/abis.go
pkg/source/lido-steth/abis/stETH.json
pkg/source/lido-steth/config.go
pkg/source/lido-steth/constant.go
pkg/source/lido-steth/embed.go
pkg/source/lido-steth/pool_tracker.go
pkg/source/lido-steth/pools/ethereum.json
pkg/source/lido-steth/pools_list_updater.go
pkg/source/lido-steth/type.go

For Lido ETH->stETH we need to get 2 reserved amounts (totalShares and totalPooledEther)
Formula in their contract code:
```
/**
* @return the amount of shares that corresponds to `_ethAmount` protocol-controlled Ether.
*/
function getSharesByPooledEth(uint256 _ethAmount) public view returns (uint256) {
return _ethAmount
.mul(_getTotalShares())
.div(_getTotalPooledEther());
}
```

[AG-364] integrate Lido eth-steth

---

pkg/source/uniswapv3/abis/UniswapV3Pool.json
pkg/source/uniswapv3/type.go

In pancake-v3, they defined feeProtocol as uint32 which is different than uniswap-v3. This is a quick and dirty solution to make the current uniswap-v3 integration fit with pancake-v3

fix: update slot0.feeProtocol from uint8 to uint32

---

pkg/source/limitorder/config.go
pkg/source/limitorder/http_client.go
pkg/source/limitorder/http_client_dto.go
pkg/source/limitorder/pool_simulator.go
pkg/source/limitorder/pool_tracker.go
pkg/source/limitorder/pools_list_updater.go
pkg/source/limitorder/type.go

Now each limit-order pool need to have info about SC address that was used to create all orders in that pool

[AG-704][AG-705] update LO pool list updater/tracker multi SCs

---

pkg/source/kyber-pmm/rfq.go
pkg/source/kyber-pmm/type.go

https://team-kyber.atlassian.net/browse/AG-756
Reason: The target in KyberRFQ struct should be the wallet who receives makerAsset, in our case it's the recipient

fix: store the recipient in RFQ extra to use in encoding

---

pkg/source/kyber-pmm/error.go
pkg/source/kyber-pmm/pool_simulator.go
pkg/source/kyber-pmm/pool_simulator_test.go

If the amount in is greater than the available amount that price levels can provide, we should return error insufficient liquidity instead of allowing the simulation to continue

fix: handle error insufficient liquidity in PMM price levels

---

pkg/source/curve/meta/pool_simulator.go

Context: https://team-kyber.slack.com/archives/C04R9NSNEKF/p1695017808835559
Summary: While `curve-meta` can swap to underlying tokens, the current `GetTokens()` function only returns the direct tokens in pools. This leads to the wrong calculate `MinHopsToTokenOut`, due to the wrong create `tokenToPoolAddress` ([code](https://github.com/KyberNetwork/router-service/blob/main/internal/pkg/usecase/findroute/spfav2/best_route.go#L32-L37)).
This PR fixes the above issue.

fix (curve-meta): add underlaying tokens in get tokens

---

.github/workflows/release.yml

Limit branch to run release to `release`.
Some notes:
- Github Action doesn't have a way to limit the select branch when triggering action with `workflow_dispatch`. I use the `if` condition to limit the release to the `release` branch. Note that, developers can always remove this line and run the workflow on their branch. Reference: https://stackoverflow.com/questions/74633548/how-to-allow-manual-workflow-dispatch-only-on-specific-branches
- Github Action doesn't support regex matching. I use `startsWith` function to check the matching branch. Reference: https://github.com/orgs/community/discussions/26186

ci: run release only on release branch

---

pkg/source/smardex/pool_simulator.go
pkg/source/smardex/pool_simulator_test.go
pkg/source/smardex/type.go

FeeToAmount and priceAverage1 is updated wrong, link to sc, [priceAverage](https://basescan.org/address/0xdd4536dD9636564D891c919416880a3e250f975A#code#F27#L212) and [feeToAmount](https://basescan.org/address/0xdd4536dD9636564D891c919416880a3e250f975A#code#F27#L306).
When UpdateBalance func miss some values, it can cause getRoute return bad result.
https://team-kyber.atlassian.net/browse/AG-1222
- Make price local storage, local pool state storage are up to date with staging.
- Follow step by step from the [ticket](https://team-kyber.atlassian.net/browse/AG-1222).
- Result: 2 APIs must return the same result despite alien-base-stableswap is include or exclude.

Update feeToAmount of smardex pool state

---

pkg/source/uniswapv3/pool_tracker.go
pkg/source/uniswapv3/queries.go
pkg/source/uniswapv3/queries_test.go

- Skip tracking empty ticks.
- Fetch all ticks instead of limit by subgraph 6000 ticks.
- Use `go-json` lib.

improvement: uniswapv3 ticks

---

pkg/source/maverickv1/errors.go
pkg/source/maverickv1/math.go
pkg/source/maverickv1/math_test.go
pkg/source/maverickv1/pool_simulator.go
pkg/source/maverickv1/pool_simulator_test.go
pkg/source/maverickv1/pool_tracker.go
pkg/source/maverickv1/type.go

Before:
`BenchmarkNextActive-8   	    6309	    189167 ns/op	   57862 B/op	    5062 allocs/op`
After:
`BenchmarkNextActive-8   	   31614	     37237 ns/op	   43612 B/op	    1063 allocs/op`

check maverick minmax binindex to reduce loop

---

pkg/source/gmx-glp/pool_simulator.go
pkg/source/gmx-glp/pool_simulator_stake.go
pkg/source/gmx-glp/pool_simulator_unstake.go

gmx-glp: make a new `gmxGlpSwapInfo` per CalcAmountOut call instead of using the shared PoolSimulator.swapInfo field

[Fix] gmx-gpl race condition

---

pkg/source/curve/aave/math.go
pkg/source/curve/aave/pool_simulator.go
pkg/source/curve/aave/pool_simulator_test.go
pkg/source/curve/base/math.go
pkg/source/curve/base/pool_simulator.go
pkg/source/curve/base/pool_simulator_test.go
pkg/source/curve/meta/math.go
pkg/source/curve/meta/pool_simulator.go
pkg/source/curve/meta/pool_simulator_test.go
pkg/source/curve/plain-oracle/math.go
pkg/source/curve/plain-oracle/pool_simulator.go
pkg/source/curve/plain-oracle/pool_simulator_test.go

Issue 1:
Curve-meta is calling `t.BasePool.GetVirtualPrice()` inside `_xp_mem` (https://github.com/KyberNetwork/kyberswap-dex-lib/pull/313/files#diff-9a159db6433983dec62bd91411fbf325a97bd332f85a4be258f0e6024303a39dR10)
But its caller always have `vPrice` calculated already, and the calculation is expensive, so we should pass from the caller instead
Issue 2:
In `GetDyUnderlying`, curve-meta will call `t.BasePool.GetVirtualPrice` then `t.BasePool.GetDy`
`t.BasePool.GetVirtualPrice` has calculated `D` already, and it's expensive, so we should return `D` in `t.BasePool.GetVirtualPrice` then pass it to `t.BasePool.GetDy` to be re-used
Benchmark:
Before
`BenchmarkGetDyUnderlying-8   	   80980	     14481 ns/op	   11297 B/op	     224 allocs/op`
After
`BenchmarkGetDyUnderlying-8   	  141639 …

reuse D and vPrice in curve-meta instead of re-calculating

---

pkg/source/curve/aave/math.go
pkg/source/curve/aave/pool_simulator.go
pkg/source/curve/aave/pool_simulator_test.go
pkg/source/curve/base/math.go
pkg/source/curve/base/pool_simulator.go
pkg/source/curve/base/pool_simulator_test.go
pkg/source/curve/meta/math.go
pkg/source/curve/meta/pool_simulator.go
pkg/source/curve/meta/pool_simulator_test.go
pkg/source/curve/plain-oracle/math.go
pkg/source/curve/plain-oracle/pool_simulator.go
pkg/source/curve/plain-oracle/pool_simulator_test.go

* reuse D and vPrice in curve-meta instead of re-calculating
* update named return params

reuse D and vPrice in curve-meta instead of re-calculating (#313)

---

pkg/liquidity-source/velocore-v2/cpmm/pool_simulator.go

shallow clone `p.Info.Reserves` to avoid race condition since `a` is going to be assigned

Fix `velocore-v2/cpmm` race condition

---

pkg/liquidity-source/velocore-v2/cpmm/pool_simulator.go

* shallow clone `p.Info.Reserves` to avoid race condition since `a` is going to be assigned
* use append() instead of slices.Clone()

Fixes to apply to release v0.27 (continue)

---

pkg/source/maverickv1/constant.go
pkg/source/maverickv1/math.go
pkg/source/maverickv1/math_test.go
pkg/source/maverickv1/pool_simulator.go
pkg/source/maverickv1/pool_simulator_test.go
pkg/source/maverickv1/type.go

Each bin crossed will cost some amount of gas, so we should take that into account as well, instead of just using flat constant (similar to univ3)

use maverick tick crossed to estimate gas

---

pkg/source/uniswapv3/pool_tracker.go
pkg/source/uniswapv3/queries.go
pkg/source/uniswapv3/queries_test.go

Include `_meta` will fail the query, even with `subgraphError: "allow"` in the query. This commit fixes this by removing the `meta` field, to support uniswap-v3 polygon which currently has indexing error.
Reference:
- Query with `_meta`: [Link](https://api.thegraph.com/subgraphs/name/ianlapham/uniswap-v3-polygon/graphql?query=%7B%0A++pool%28subgraphError%3A+allow%2C+id%3A+%220x6bad0f9a89ca403bb91d253d385cec1a2b6eca97%22%29+%7B%0A++++id%0A++++feeTier%0A++++ticks%28%0A++++++where%3A+%7BliquidityGross_not%3A+0%7D%0A++++++orderBy%3A+tickIdx%0A++++++orderDirection%3A+asc%0A++++++first%3A+1000%0A++++%29+%7B%0A++++++tickIdx%0A++++++liquidityNet%0A++++++liquidityGross%0A++++%7D%0A++%7D%0A++_meta%7Bblock%7Bnumber%7D%7D%0A%7D#)
- Query without `_meta`: …

fix: ignore meta when query pools from subgraph

---

pkg/source/uniswapv3/constant.go
pkg/source/uniswapv3/pool_tracker.go
pkg/source/uniswapv3/queries.go
pkg/source/uniswapv3/queries_test.go

Change the fetch ticks query to be compatible with the new Polygon UniswapV3 error-fixed subgraph.
The logic also compatible with previous subgraphs.

chore: update fetch ticks in uniswapv3

---

pkg/liquidity-source/curve/plain/constant.go
pkg/liquidity-source/curve/plain/math.go
pkg/liquidity-source/curve/plain/pool_simulator_test.go

we're having 2 issues:
- if pool has zero balance then output amount is very large: caused by underflow in subtraction, fixed in this pr
- if pool balance is skewed then onchain SC will yield error because of multiplying overflow, but our simulation still return ok, this is NOT fixed, because to fix that we would have added safemath everywhere, and the output amount in this case is small anyway

fix curve plain integer underflow

---

pkg/liquidity-source/uniswap-v2/pool_simulator.go
pkg/liquidity-source/uniswap-v2/pool_simulator_test.go
pkg/liquidity-source/uniswap-v2/safe_math.go
pkg/liquidity-source/uniswap-v2/safe_math_test.go

Without SafeMath implementation, this pool https://polygonscan.com/address/0x96c7fc08d8cdacdb95a8613b19fffe4d54307263#code still gives a valid amount in = `1` for getAmountin() function with params:
```
reserveIn:        number.NewUint256("1160689189059097452"),
reserveOut:       number.NewUint256("1161607"),
amountOut:        number.NewUint256("500000000"),
```
But in reality, it should revert with the error `ds-math-sub-underflow`
This incorrect behavior breaks the CalcAmountIn function in onchain-price-service

fix: uniswap-v2 safe math

---

go.mod
go.sum
pkg/source/uniswapv3/pool_simulator.go
pkg/source/uniswapv3/pool_simulator_test.go

Benchmark:
Before (after part1 https://github.com/KyberNetwork/kyberswap-dex-lib/pull/322)
```
BenchmarkCalcAmountOutV2-8                	  112780	     10659 ns/op	   11472 B/op	     180 allocs/op
BenchmarkCalcAmountOutCrossFewTickV2-8    	   67615	     17725 ns/op	   17877 B/op	     334 allocs/op
BenchmarkCalcAmountOutCrossManyTickV2-8   	   10000	    104921 ns/op	   96741 B/op	    2285 allocs/op
```
After (after this PR)
```
BenchmarkCalcAmountOutV2-8                	  240918	      4977 ns/op	    3088 B/op	      40 allocs/op
BenchmarkCalcAmountOutCrossFewTickV2-8    	  112432	     10670 ns/op	    3088 B/op	      40 allocs/op
BenchmarkCalcAmountOutCrossManyTickV2-8   	   16384	     73133 ns/op	    3089 B/op	      40 allocs/op
```

optimize univ3 logic and alloc

---

pkg/liquidity-source/ambient/pool_list_updater.go
pkg/liquidity-source/ambient/pool_list_updater_test.go

fixed ambient.PoolListUpdater.GetNewPools() returns error when metadataBytes=nil

---

pkg/liquidity-source/ambient/types.go

implement missing CanSwapFrom for ambient.NTokenPool

---

pkg/liquidity-source/curve/stable-meta-ng/pool_simulator.go
pkg/liquidity-source/curve/stable-meta-ng/pool_simulator_test.go
pkg/source/curve/meta/pool_simulator.go
pkg/source/curve/meta/pool_simulator_test.go

EX-2253: disallow swapping through underlaying tokens in curve-meta

---

pkg/source/nuriv2/pool_tracker.go
pkg/source/nuriv2/pools_list_updater.go
pkg/source/nuriv2/type.go
pkg/source/pancakev3/pools_list_updater.go
pkg/source/ramsesv2/pool_tracker.go
pkg/source/ramsesv2/pools_list_updater.go
pkg/source/ramsesv2/type.go
pkg/source/slipstream/pools_list_updater.go
pkg/source/solidly-v3/pool_tracker.go
pkg/source/solidly-v3/pools_list_updater.go
pkg/source/solidly-v3/type.go
pkg/source/uniswapv3/constant.go
pkg/source/uniswapv3/pools_list_updater.go
pkg/source/uniswapv3/util.go

EX-2312: init tick spacing when list pool

---

pkg/liquidity-source/fluid/dex-t1/pool_simulator.go
pkg/liquidity-source/fluid/dex-t1/pool_simulator_test.go

Add logic updating reserves after CalAmount in Fluid-Dex

---

pkg/liquidity-source/clipper/pool_simulator.go
pkg/liquidity-source/clipper/rfq.go
pkg/liquidity-source/clipper/type.go

Javascript will cast incorrectly when the number is too large. To avoid it, when returning int64 data to the client (in this case, the `InputAmount`), we will return the string form instead.

fix: cast uint64 to string in swap info

---

pkg/source/algebrav1/abis.go
pkg/source/algebrav1/abis/TickLens.json
pkg/source/algebrav1/config.go
pkg/source/algebrav1/embed.go
pkg/source/algebrav1/errors.go
pkg/source/algebrav1/pool_tracker.go
pkg/source/algebrav1/ticklens.go
pkg/source/pancakev3/pool_tracker.go
pkg/source/ramsesv2/pool_tracker.go
pkg/source/uniswapv3/pool_tracker.go
pkg/util/ticklens/Events.json
pkg/util/ticklens/abis.go
pkg/util/ticklens/ticklens.go

Algebra doesn't have Ticklens contract deployed, so we need to use a custom one. Currently Algebra doesn't compact the ticktable, so we can only get a small number of ticks for now
This PR also update univ3-clones to support only re-fetching changed ticks (parsed from log)

support algebra ticklens

---

pkg/liquidity-source/hashflow-v3/pool_simulator.go
pkg/liquidity-source/hashflow-v3/pool_simulator_test.go

Implement `CalcAmountIn` function for hashflow-v3 pool simulator.
To support more exact output orders routed via hashflow-v3
- https://team-kyber.atlassian.net/browse/TRD-742

Implement CalcAmountIn for hashflow-v3

---

pkg/liquidity-source/lo1inch/config.go
pkg/liquidity-source/lo1inch/constant.go
pkg/liquidity-source/lo1inch/errors.go
pkg/liquidity-source/lo1inch/pool_simulator.go
pkg/liquidity-source/lo1inch/pool_simulator_test.go
pkg/liquidity-source/lo1inch/rfq.go
pkg/liquidity-source/lo1inch/type.go
pkg/msgpack/register_pool_types.go
pkg/pooltypes/pooltypes.go
pkg/util/bignumber/bignumber.go
pkg/valueobject/exchange.go

https://team-kyber.atlassian.net/browse/EX-2407

feat: integrate 1inch limit order v4

---

pkg/liquidity-source/mx-trading/pool_simulator.go
pkg/liquidity-source/mx-trading/pool_simulator_test.go

Reduce each token's reserve by 5% to prevent the total quote amount of a token from potentially exceeding the maker's balance when building the route

fix(mx-trading): reduce inventory limit

---

pkg/source/limitorder/pool_simulator.go
pkg/source/limitorder/pool_simulator_test.go

This reverts commit 90de6a5d310bce447c32b63e52fb0a204249a526.
The correct amount will be calculated by SC instead of BE. The reason is that if the LO pool is not the 1st swap, SC will have to calculate the takerAsset fee by themself anyway (from amountOut of previous swap)

Revert "fix LO swapInfo.AmountIn in case take fee in takerAsset (#644)"

---

pkg/liquidity-source/lo1inch/pool_simulator.go
pkg/liquidity-source/lo1inch/pool_simulator_test.go
pkg/liquidity-source/lo1inch/type.go
pkg/util/big256/big256.go

refactor: use uint256 instead of *big.Int for 1inch limit order

---

pkg/liquidity-source/fluid/dex-t1/abis/dexReservesResolver.json
pkg/liquidity-source/fluid/dex-t1/constant.go
pkg/liquidity-source/fluid/dex-t1/pool_list_updater.go
pkg/liquidity-source/fluid/dex-t1/pool_list_updater_test.go
pkg/liquidity-source/fluid/dex-t1/pool_simulator.go
pkg/liquidity-source/fluid/dex-t1/pool_simulator_test.go
pkg/liquidity-source/fluid/dex-t1/pool_tracker.go
pkg/liquidity-source/fluid/dex-t1/pool_tracker_test.go
pkg/liquidity-source/fluid/dex-t1/types.go

improves pool reserves ratio verification check by using the pool center price, properly simulating the on-chain flow. buffer margin is reduced to 2e4 which is still double the on-chain 1e4

fluid: add center price for verify reserves

---

pkg/liquidity-source/deltaswap-v1/pool_list_updater.go
pkg/liquidity-source/ether-vista/pool_list_updater.go
pkg/liquidity-source/ringswap/pool_list_updater.go
pkg/liquidity-source/solidly-v2/pool_list_updater.go
pkg/liquidity-source/swap-x-v2/pool_list_updater.go
pkg/liquidity-source/uniswap-v1/pool_list_updater.go
pkg/liquidity-source/uniswap-v2/pool_list_updater.go
pkg/liquidity-source/velodrome-v1/pool_list_updater.go
pkg/liquidity-source/velodrome-v2/pool_list_updater.go
pkg/liquidity-source/virtual-fun/pool_list_updater.go

Our system retrieves the latest "allPairsLength." Reverted blocks may cause the "allPairsLength" in our system to be greater than the actual value on the blockchain, causing the "batchSize" to return a negative value and causing panic.

fix: fix possible panic with batchSize

---

pkg/source/iziswap/snapshot.go

Use the built-in max/min from the standard library in Go 1.21 to simplify the code.  https://pkg.go.dev/builtin@go1.21.0#max

refactor: use the built-in max/min to simplify the code

---

pkg/source/uniswapv3/pool_simulator.go
pkg/source/uniswapv3/type.go

Currently, we need `NextStateSqrtRatioX96` at some internal services. But it didn't return in router API due to this field is private.
- Set `NextStateSqrtRatioX96` as public field

feat(*): expose NextStateSqrtRatioX96 field in swapInfo

---

pkg/liquidity-source/bebop/client/http.go

When an error occurs when calling rfq, bebop still return error response with http status is 200. So I update to handle it.

fix: Handle bebop call rfq fail
