KyberNetwork/kyberswap-dex-lib

pkg/source/fraxswap/constant.go, pkg/source/fraxswap/pool_simulator.go, pkg/source/fraxswap/pool_simulator_test.go, pkg/source/fraxswap/type.go, pkg/util/bignumber/bignumber.go
https://team-kyber.atlassian.net/browse/AG-342
=> [AG-342] copy fraxswap pool simulator from router-service

pkg/source/curve/pool_base.go
this method should call the contract instead of the token
https://etherscan.io/address/0x1005f7406f32a61bd760cfa14accd2737913d546#readContract
=> fix curve-base totalSupply call

go.mod, go.sum, pkg/source/dmm/constant.go, pkg/source/dmm/math.go, pkg/source/dmm/math_test.go, pkg/source/dmm/pool_simulator.go, pkg/source/dmm/pool_simulator_test.go, pkg/source/dmm/type.go, pkg/source/uniswapv3/constant.go, pkg/source/uniswapv3/math.go, pkg/source/uniswapv3/pool_simulator.go, pkg/source/uniswapv3/pool_tracker.go, pkg/source/uniswapv3/pools_list_updater.go, pkg/source/uniswapv3/type.go
- https://team-kyber.atlassian.net/browse/AG-340
- https://team-kyber.atlassian.net/browse/AG-354
=> feat: add uniswapv3 + dmm simulation logic

pkg/source/elastic/pool_simulator.go, pkg/source/uniswapv3/pool_simulator.go
- https://team-kyber.slack.com/archives/C054H6WG7EV/p1686646428833669
- https://team-kyber.slack.com/archives/C04R9NSNEKF/p1686655451837519
=> fix: skip pools with nil Tick (uniswapv3 + elastic)

pkg/source/curve/pools_list_updater.go, pkg/source/platypus/pools_list_updater.go
Avalanche address provider is returning zero for offset 6 (crypto factory)
=> ignore zero registry/factory for curve pools

pkg/source/curve/constant.go, pkg/source/curve/embed.go, pkg/source/curve/helper.go, pkg/source/curve/pool_base.go, pkg/source/curve/pool_tracker.go, pkg/source/curve/pools/ellipsis/bsc.json, pkg/source/curve/pools_list_updater.go
Related bug: https://team-kyber.atlassian.net/browse/AG-452
=> feat: integrate ellipsis

pkg/source/oneswap/abi/ERC20.json, pkg/source/oneswap/abis.go, pkg/source/oneswap/constant.go, pkg/source/oneswap/embed.go, pkg/source/oneswap/pool_tracker.go, pkg/source/oneswap/pools_list_updater.go
oneswap is using saddle pool simulator, which expect totalSupply (to be able to swap to/from lpToken)
=> get lptoken totalSupply for oneswap

pkg/source/curve/pool_tricrypto.go
Issue: https://team-kyber.atlassian.net/browse/AG-473
=> fix: curve-tricrypto priceScales, priceOracles, lastPrices incorrect length

pkg/source/makerpsm/constant.go, pkg/source/makerpsm/pool_simulator.go, pkg/source/makerpsm/pool_simulator_test.go, pkg/source/makerpsm/psm.go, pkg/source/makerpsm/type.go, pkg/source/makerpsm/vat.go, pkg/util/bignumber/bignumber.go
https://team-kyber.atlassian.net/browse/AG-347
(testcases are from https://github.com/makerdao/dss-psm/blob/master/src/tests/psm.t.sol)
=> [AG-347] copy makerpsm from router-service and add test

pkg/source/camelot/constant.go, pkg/source/camelot/math.go, pkg/source/camelot/pool_simulator.go, pkg/source/camelot/pool_simulator_test.go, pkg/source/camelot/type.go, pkg/util/bignumber/bignumber.go
https://team-kyber.atlassian.net/browse/AG-332
=> [AG-332] add camelot simulation logic

pkg/source/balancer/constant.go, pkg/source/balancer/pool_tracker.go, pkg/source/balancer/stable/math.go, pkg/source/balancer/stable/pool_simulator.go, pkg/source/balancer/stable/pool_simulator_test.go, pkg/source/balancer/type.go, pkg/source/balancer/weighted/constant.go, pkg/source/balancer/weighted/fixedpoint.go, pkg/source/balancer/weighted/formula.go, pkg/source/balancer/weighted/math.go, pkg/source/balancer/weighted/pool_simulator.go, pkg/source/balancer/weighted/pool_simulator_test.go
https://team-kyber.atlassian.net/browse/AG-330
https://team-kyber.atlassian.net/browse/AG-331
=> [AG-330] [AG-331] add balancer dex (stable and weighted)

pkg/source/lido-steth/constant.go, pkg/source/lido-steth/pool_simulator.go, pkg/source/lido-steth/pool_simulator_test.go, pkg/source/pool/iface.go, pkg/source/pool/pool.go
(depends on https://github.com/KyberNetwork/kyberswap-dex-lib/pull/20)
=> [AG-365] add pool simulator for Lido eth-steth

pkg/source/saddle/constant.go, pkg/source/saddle/math.go, pkg/source/saddle/math_test.go, pkg/source/saddle/pool_simulator.go, pkg/source/saddle/pool_simulator_test.go, pkg/source/saddle/type.go, pkg/util/bignumber/bignumber.go
(used for saddle and iron-stable, oneswap, nerve)
=> [AG-351] add saddle simulation logic

pkg/source/curve/aave/constant.go, pkg/source/curve/aave/error.go, pkg/source/curve/aave/math.go, pkg/source/curve/aave/math_test.go, pkg/source/curve/aave/pool_simulator.go, pkg/source/curve/aave/pool_simulator_test.go
(this PR depends on https://github.com/KyberNetwork/kyberswap-dex-lib/pull/16)
=> [AG-333] add curve-aave simulation logic

pkg/source/syncswap/pools_list_updater.go, pkg/source/syncswap/syncswapclassic/constant.go, pkg/source/syncswap/syncswapclassic/math.go, pkg/source/syncswap/syncswapclassic/pool_simulator.go, pkg/source/syncswap/syncswapclassic/pool_simulator_test.go, pkg/source/syncswap/syncswapstable/constant.go, pkg/source/syncswap/syncswapstable/math.go, pkg/source/syncswap/syncswapstable/pool_simulator.go, pkg/source/syncswap/syncswapstable/pool_simulator_test.go, pkg/source/syncswap/type.go
=> [AG-555] [AG-556] add syncswapclassic and syncswapstable simulator

pkg/source/maverickv1/math.go, pkg/source/maverickv1/pool_simulator.go
=> [AG-521] update pool simulator for maverick

pkg/entity/pool.go, pkg/source/pool/pool.go, pkg/source/synthetix/pool_simulator.go
=> refactor: add necessary methods for pool

pkg/source/elastic/constant.go, pkg/source/elastic/pool_simulator.go, pkg/source/pancakev3/constant.go, pkg/source/pancakev3/pool_simulator.go, pkg/source/uniswapv3/constant.go, pkg/source/uniswapv3/pool_simulator.go
=> fix: swap fee uniswapv3

pkg/source/maverickv1/math.go
=> fix bug: wrong update balance

pkg/source/maverickv1/math.go
=> Fix bug: maverick update balance

pkg/source/maverickv1/pool_simulator.go, pkg/source/maverickv1/pool_tracker.go, pkg/source/maverickv1/type.go
=> maverick: not update binPos of mergeID not equals 0

pkg/source/maverickv1/pool_simulator.go, pkg/source/maverickv1/pool_tracker.go, pkg/source/maverickv1/type.go
=> [Release] maverick: not update binPos of mergeID not equals 0

pkg/source/handler.go, pkg/source/pearl/abi/Factory.json, pkg/source/pearl/abi/Pair.json, pkg/source/pearl/abis.go, pkg/source/pearl/config.go, pkg/source/pearl/constant.go, pkg/source/pearl/embed.go, pkg/source/pearl/helper.go, pkg/source/pearl/pool_tracker.go, pkg/source/pearl/pools_list_updater.go, pkg/source/pearl/type.go, pkg/valueobject/exchange.go
=> AG-588: integrate pearl

pkg/source/handler.go, pkg/source/pearl/abi/Factory.json, pkg/source/pearl/abi/Pair.json, pkg/source/pearl/abis.go, pkg/source/pearl/config.go, pkg/source/pearl/constant.go, pkg/source/pearl/embed.go, pkg/source/pearl/helper.go, pkg/source/pearl/pool_tracker.go, pkg/source/pearl/pools_list_updater.go, pkg/source/pearl/type.go, pkg/valueobject/exchange.go
=> [Release] AG-588: Integrate pearl

pkg/source/maverickv1/pool_tracker.go
=> [Release] Maverick: remove unused bins (#90)

pkg/source/uniswapv3/pool_tracker.go, pkg/source/uniswapv3/pools_list_updater.go
=> chore: using dex id for uniswap v3 log

pkg/source/uniswapv3/pool_tracker.go, pkg/source/uniswapv3/pools_list_updater.go
=> chore: using dex id for uniswap v3 log (#98)

pkg/source/maverickv1/pool_tracker.go, pkg/source/maverickv1/type.go
=> maverick: calculate tvl

pkg/source/maverickv1/pool_tracker.go, pkg/source/maverickv1/type.go
=> [Release] maverick: calculate tvl

pkg/entity/price.go, pkg/entity/price_test.go
https://team-kyber.slack.com/archives/C054H6WG7EV/p1691138619840979?thread_ts=1691137595.464019&cid=C054H6WG7EV
=> feat: add sanity price check

go.mod, go.sum, pkg/source/algebrav1/adaptive_fee.go, pkg/source/algebrav1/config.go, pkg/source/algebrav1/data_storage.go, pkg/source/algebrav1/pool_tracker.go, pkg/util/bignumber/bignumber.go
=> [AG-612] algebrav1 fee approximation

go.mod, go.sum, pkg/source/algebrav1/adaptive_fee.go, pkg/source/algebrav1/config.go, pkg/source/algebrav1/constant.go, pkg/source/algebrav1/data_storage.go, pkg/source/algebrav1/pool_tracker.go, pkg/source/handler.go, pkg/util/bignumber/bignumber.go
=> [AG-610] pool state tracker for algebrav1

go.mod, go.sum, pkg/source/algebrav1/abis.go, pkg/source/algebrav1/abis/AlgebraV1DataStorageOperator.json, pkg/source/algebrav1/abis/AlgebraV1Pool.json, pkg/source/algebrav1/abis/ERC20.json, pkg/source/algebrav1/adaptive_fee.go, pkg/source/algebrav1/config.go, pkg/source/algebrav1/constant.go, pkg/source/algebrav1/data_storage.go, pkg/source/algebrav1/embed.go, pkg/source/algebrav1/errors.go, pkg/source/algebrav1/pool_list_updater.go, pkg/source/algebrav1/pool_tracker.go, pkg/source/algebrav1/queries.go, pkg/source/algebrav1/type.go, pkg/source/handler.go, pkg/util/bignumber/bignumber.go
=> [AG-609] pool list updater for algebrav1

go.mod, go.sum, pkg/source/algebrav1/pool_list_updater.go, pkg/source/elastic/pools_list_updater.go, pkg/source/pancakev3/pools_list_updater.go, pkg/source/uniswapv3/pools_list_updater.go
=> avoid overriding bignumber zero

go.mod, go.sum, pkg/source/algebrav1/math.go, pkg/source/algebrav1/pool_simulator.go, pkg/source/algebrav1/pool_simulator_test.go
=> [AG-611] pool simulator for algebrav1

pkg/source/algebrav1/abis.go, pkg/source/algebrav1/abis/AlgebraV1DirFeeDataStorageOperator.json, pkg/source/algebrav1/abis/AlgebraV1PoolDirectionalFee.json, pkg/source/algebrav1/config.go, pkg/source/algebrav1/constant.go, pkg/source/algebrav1/embed.go, pkg/source/algebrav1/math.go, pkg/source/algebrav1/pool_simulator_test.go, pkg/source/algebrav1/pool_tracker.go, pkg/source/algebrav1/type.go
=> [AG-614] support algebrav1 camelot (directional fee)

pkg/source/balancer/pools_list_updater.go
=> fix weight balancer in pool_list_updater

pkg/source/maverickv1/pool_simulator_test.go, pkg/source/maverickv1/pool_tracker.go
Changes:
- add test cases
- missing the last state
=> [Main] Fix maverick bugs: missing the last state

pkg/source/maverickv1/pool_simulator_test.go, pkg/source/maverickv1/pool_tracker.go
Changes:
- add test cases
- missing the last state
=> [Release] Fix maverick bugs: missing the last state

pkg/source/maverickv1/pool_simulator_test.go, pkg/source/maverickv1/pool_tracker.go
=> [Release] fix: maverick rate, delete the bin has reserveA and reserveB equals 0

pkg/source/maverickv1/pool_simulator_test.go, pkg/source/maverickv1/pool_tracker.go
=> [MAIN] fix: maverick rate, delete the bin has reserveA and reserveB equals 0

pkg/source/balancer-composable-stable/errors.go, pkg/source/balancer-composable-stable/math.go, pkg/source/balancer-composable-stable/pool_simulator.go, pkg/source/balancer-composable-stable/pool_simulator_test.go
=> add error catching and unit test for calcInvariant

pkg/source/balancer-composable-stable/errors.go, pkg/source/balancer-composable-stable/math.go, pkg/source/balancer-composable-stable/pool_simulator.go, pkg/source/balancer-composable-stable/pool_simulator_test.go
* add error catching and unit test for calcInvariant
* remove logger warn
* add check amountOutCalculated nil
=> add error catching and unit test for calcInvariant (#110)

pkg/source/maverickv1/math.go, pkg/source/maverickv1/pool_simulator.go
=> AG-645: fix bug invalid swap

pkg/source/maverickv1/math.go, pkg/source/maverickv1/pool_simulator.go
=> AG-645: fix bug invalid swap 

CHANGELOG.md
=> changelog: release v0.10.1

pkg/source/saddle/pools/synapse/base.json
=> [Release] lowercase synapse config file

pkg/source/saddle/pools/synapse/base.json
=> lowercase synapse config file

CHANGELOG.md
=> changelog: release v0.10.2

pkg/source/balancer-composable-stable/pool_simulator.go, pkg/source/balancer-composable-stable/type.go, pkg/source/balancer/stable/pool_simulator.go, pkg/source/balancer/type.go, pkg/source/balancer/weighted/pool_simulator.go
* feat: add mapping token address for balancer
related: AG-775
* feat: move mapping outside for new pool
=> feat: add mapping token address for balancer (#119)

pkg/source/handler.go, pkg/source/velodromev2/abi/Factory.json, pkg/source/velodromev2/abi/Pair.json, pkg/source/velodromev2/abis.go, pkg/source/velodromev2/config.go, pkg/source/velodromev2/constant.go, pkg/source/velodromev2/embed.go, pkg/source/velodromev2/helper.go, pkg/source/velodromev2/math.go, pkg/source/velodromev2/math_test.go, pkg/source/velodromev2/pool_simulator.go, pkg/source/velodromev2/pool_simulator_test.go, pkg/source/velodromev2/pool_tracker.go, pkg/source/velodromev2/pools_list_updater.go, pkg/source/velodromev2/type.go
=> Integrate velodromev2

pkg/source/handler.go, pkg/source/velodromev2/abi/Factory.json, pkg/source/velodromev2/abi/Pair.json, pkg/source/velodromev2/abis.go, pkg/source/velodromev2/config.go, pkg/source/velodromev2/constant.go, pkg/source/velodromev2/embed.go, pkg/source/velodromev2/helper.go, pkg/source/velodromev2/math.go, pkg/source/velodromev2/math_test.go, pkg/source/velodromev2/pool_simulator.go, pkg/source/velodromev2/pool_simulator_test.go, pkg/source/velodromev2/pool_tracker.go, pkg/source/velodromev2/pools_list_updater.go, pkg/source/velodromev2/type.go
=> [Release] Integrate velodromev2

go.mod, go.sum, pkg/source/handler.go, pkg/source/kyber-pmm/client/error.go, pkg/source/kyber-pmm/client/http.go, pkg/source/kyber-pmm/client/memory_cache.go, pkg/source/kyber-pmm/config.go, pkg/source/kyber-pmm/constant.go, pkg/source/kyber-pmm/error.go, pkg/source/kyber-pmm/iface.go, pkg/source/kyber-pmm/pool_simulator.go, pkg/source/kyber-pmm/pool_simulator_test.go, pkg/source/kyber-pmm/pool_tracker.go, pkg/source/kyber-pmm/pools_list_updater.go, pkg/source/kyber-pmm/type.go
Add pools list updater, pool tracker and pool simulator for Kyber PMM
Encoding logic should be handle in a separate PR
- https://team-kyber.atlassian.net/browse/AG-753
- https://team-kyber.atlassian.net/browse/AG-754
- https://team-kyber.atlassian.net/browse/AG-755
At the moment, just use the unit tests inside
=> feat: integrate Kyber PMM

pkg/entity/bestpath.go
=> Add bestPaths entity for pregen service

pkg/source/curve/config.go, pkg/source/curve/constant.go, pkg/source/curve/embed.go, pkg/source/curve/helper.go, pkg/source/curve/pool_tracker.go, pkg/source/curve/pools/base.json, pkg/source/curve/pools/pancake-stable/bsc.json, pkg/source/curve/pools_list_updater.go, pkg/valueobject/exchange.go
=> pancake-stable on Bsc and curve on Base

pkg/source/curve/config.go, pkg/source/curve/constant.go, pkg/source/curve/embed.go, pkg/source/curve/helper.go, pkg/source/curve/pool_tracker.go, pkg/source/curve/pools/base.json, pkg/source/curve/pools/pancake-stable/bsc.json, pkg/source/curve/pools_list_updater.go, pkg/valueobject/exchange.go
* bsc: pancake-stable
* base: curve json config
=> [Release] pancake-stable on Bsc and curve on Base 

CHANGELOG.md
=> changelog: release v0.10.4

pkg/source/saddle/embed.go, pkg/source/saddle/pools/alien-base-stableswap/base.json
=> feat: integrate alien-base-stableswap

pkg/source/curve/pools/base.json
=> base: update curve config

pkg/source/curve/pools/base.json
=> [Release] base: update curve config

pkg/source/biswap/config.go, pkg/source/biswap/pool_tracker.go
=> feat: configurable fee precision for biswap

pkg/source/biswap/config.go, pkg/source/biswap/pool_tracker.go
=> feat: configurable fee precision for biswap (#144)

pkg/source/kyber-pmm/rfq.go, pkg/source/limitorder/rfq.go, pkg/source/pool/iface.go
Due to this discussion https://www.notion.so/kybernetwork/Build-route-behavior-discussion-5a0765555e1e47c1866db5df3d01a0b5?pvs=4, we need to calculate the new amount out after doing RFQ.
If the new amountOut is smaller than the estimated amountOut via Get Routes use case, we should return error at the moment
=> refactor: change interface of RFQ function

pkg/source/curve/meta/pool_simulator.go
=> fix (curve-meta): add underlaying tokens in get tokens (#148)

pkg/source/kyber-pmm/client/error.go, pkg/source/kyber-pmm/client/http.go, pkg/source/kyber-pmm/type.go
=> refactor: handle errors from /firm API

pkg/source/velocimeter/constant.go, pkg/source/wombat/abi/Asset.json, pkg/source/wombat/abi/DynamicAsset.json, pkg/source/wombat/abi/PoolV2.json, pkg/source/wombat/abis.go, pkg/source/wombat/config.go, pkg/source/wombat/constant.go, pkg/source/wombat/embed.go, pkg/source/wombat/pool_tracker.go, pkg/source/wombat/pools_list_updater.go, pkg/source/wombat/type.go, pkg/source/wombat/wombatlsd/constant.go, pkg/source/wombat/wombatlsd/errors.go, pkg/source/wombat/wombatlsd/math.go, pkg/source/wombat/wombatlsd/math_test.go, pkg/source/wombat/wombatlsd/pool_simulator.go, pkg/source/wombat/wombatmain/constant.go, pkg/source/wombat/wombatmain/errors.go, pkg/source/wombat/wombatmain/math.go, pkg/source/wombat/wombatmain/math_test.go, pkg/source/wombat/wombatmain/pool_simulator.go
=> [AG-666]: Wombat simulator

pkg/source/velocimeter/constant.go, pkg/source/wombat/abi/Asset.json, pkg/source/wombat/abi/DynamicAsset.json, pkg/source/wombat/abi/PoolV2.json, pkg/source/wombat/abis.go, pkg/source/wombat/config.go, pkg/source/wombat/constant.go, pkg/source/wombat/embed.go, pkg/source/wombat/pool_tracker.go, pkg/source/wombat/pools_list_updater.go, pkg/source/wombat/type.go, pkg/source/wombat/wombatlsd/constant.go, pkg/source/wombat/wombatlsd/errors.go, pkg/source/wombat/wombatlsd/math.go, pkg/source/wombat/wombatlsd/math_test.go, pkg/source/wombat/wombatlsd/pool_simulator.go, pkg/source/wombat/wombatmain/constant.go, pkg/source/wombat/wombatmain/errors.go, pkg/source/wombat/wombatmain/math.go, pkg/source/wombat/wombatmain/math_test.go, pkg/source/wombat/wombatmain/pool_simulator.go
=> AG-666: wombat-main and wombat-lsd (#112)

pkg/source/pool/iface.go
=> Correct PoolTracker interface

pkg/source/kyber-pmm/pool_simulator.go
=> fix (pmm): token decimals doesn't persist

pkg/source/curve/pools/pancake-stable/bsc.json
=> AG-921: update pancake-stable config

pkg/source/kyber-pmm/rfq.go
=> refactor: validate RFQ params to avoid redundant /firm request

pkg/source/woofiv2/abi/ERC20.json, pkg/source/woofiv2/abi/IntegrationHelper.json, pkg/source/woofiv2/abi/WooPPV2.json, pkg/source/woofiv2/abi/WooracleV2.json, pkg/source/woofiv2/abis.go, pkg/source/woofiv2/config.go, pkg/source/woofiv2/constant.go, pkg/source/woofiv2/embed.go, pkg/source/woofiv2/errors.go, pkg/source/woofiv2/math.go, pkg/source/woofiv2/math_test.go, pkg/source/woofiv2/pool_simulator.go, pkg/source/woofiv2/pool_tracker.go, pkg/source/woofiv2/pools_list_updater.go, pkg/source/woofiv2/type.go
=> WoofiV2: pool_simulator, pools_list_updater, pool_tracker

pkg/source/curve/pools/pancake-stable/bsc.json
=> [Release] [AG-921] update pancake-stable config 

pkg/source/wombat/abi/CrossChainPool.json, pkg/source/wombat/abis.go, pkg/source/wombat/constant.go, pkg/source/wombat/embed.go, pkg/source/wombat/pool_tracker.go, pkg/source/wombat/pools_list_updater.go, pkg/source/wombat/type.go, pkg/source/wombat/wombatlsd/errors.go, pkg/source/wombat/wombatlsd/math.go, pkg/source/wombat/wombatlsd/math_test.go, pkg/source/wombat/wombatlsd/pool_simulator.go, pkg/source/wombat/wombatmain/errors.go, pkg/source/wombat/wombatmain/math.go, pkg/source/wombat/wombatmain/math_test.go, pkg/source/wombat/wombatmain/pool_simulator.go
=> Fix: isPaused field not found on old pools and classify crossChainPool

pkg/source/wombat/abi/CrossChainPool.json, pkg/source/wombat/abis.go, pkg/source/wombat/constant.go, pkg/source/wombat/embed.go, pkg/source/wombat/pool_tracker.go, pkg/source/wombat/pools_list_updater.go, pkg/source/wombat/type.go, pkg/source/wombat/wombatlsd/errors.go, pkg/source/wombat/wombatlsd/math.go, pkg/source/wombat/wombatlsd/math_test.go, pkg/source/wombat/wombatlsd/pool_simulator.go, pkg/source/wombat/wombatmain/errors.go, pkg/source/wombat/wombatmain/math.go, pkg/source/wombat/wombatmain/math_test.go, pkg/source/wombat/wombatmain/pool_simulator.go
=> Fix: isPaused field not found on old pools and classify crossChain

pkg/source/iziswap/pool_simulator.go
=> fix: not mutate amount in for iziswap

pkg/source/iziswap/pool_simulator.go
=> fix: not mutate amount in for iziswap (#166)

pkg/entity/pool.go, pkg/source/wombat/pool_tracker.go
=> Release: Update hasReserves()

go.mod, go.sum, pkg/source/uniswap/pool_tracker.go, pkg/source/uniswap/uniswap_pair.go
Update uniswap v2 reserves from event
=> Update uniswap v2 reserves from event

pkg/source/wombat/pool_tracker.go
=> Wombat: set default reserve value

pkg/source/algebrav1/pool_tracker.go, pkg/source/algebrav1/queries.go, pkg/source/elastic/pool_tracker.go, pkg/source/pancakev3/pool_tracker.go, pkg/source/pancakev3/queries.go, pkg/source/pancakev3/queries_test.go, pkg/source/uniswapv3/pool_tracker.go, pkg/source/uniswapv3/queries.go, pkg/source/uniswapv3/queries_test.go, pkg/source/wombat/pool_tracker.go, pkg/valueobject/subgraph.go
=> query and check subgraph pool-tick lag

pkg/source/algebrav1/pool_tracker.go, pkg/source/algebrav1/queries.go, pkg/source/elastic/pool_tracker.go, pkg/source/pancakev3/pool_tracker.go, pkg/source/pancakev3/queries.go, pkg/source/pancakev3/queries_test.go, pkg/source/uniswapv3/pool_tracker.go, pkg/source/uniswapv3/queries.go, pkg/source/uniswapv3/queries_test.go, pkg/source/wombat/pool_tracker.go, pkg/valueobject/subgraph.go
=> query and check subgraph pool-tick lag (#168)

pkg/source/pool/iface.go, pkg/source/pool/pool.go
=> refactor: expose get reserves for pool interface

pkg/source/usdfi/abi/Factory.json, pkg/source/usdfi/abi/Pair.json, pkg/source/usdfi/abis.go, pkg/source/usdfi/config.go, pkg/source/usdfi/constant.go, pkg/source/usdfi/embed.go, pkg/source/usdfi/helper.go, pkg/source/usdfi/math.go, pkg/source/usdfi/math_test.go, pkg/source/usdfi/pool_simulator.go, pkg/source/usdfi/pool_simulator_test.go, pkg/source/usdfi/pool_tracker.go, pkg/source/usdfi/pools_list_updater.go, pkg/source/usdfi/type.go
Resolves https://team-kyber.atlassian.net/browse/AG-1085
=> feat: support usdfi

pkg/source/mantisswap/abi/LP.json, pkg/source/mantisswap/abi/MainPool.json, pkg/source/mantisswap/abis.go, pkg/source/mantisswap/config.go, pkg/source/mantisswap/constant.go, pkg/source/mantisswap/embed.go, pkg/source/mantisswap/errors.go, pkg/source/mantisswap/math.go, pkg/source/mantisswap/math_test.go, pkg/source/mantisswap/pool_simulator.go, pkg/source/mantisswap/pool_tracker.go, pkg/source/mantisswap/pools_list_updater.go, pkg/source/mantisswap/type.go
=> Integrate: mantisswap

pkg/source/mantisswap/abi/LP.json, pkg/source/mantisswap/abi/MainPool.json, pkg/source/mantisswap/abis.go, pkg/source/mantisswap/config.go, pkg/source/mantisswap/constant.go, pkg/source/mantisswap/embed.go, pkg/source/mantisswap/errors.go, pkg/source/mantisswap/math.go, pkg/source/mantisswap/math_test.go, pkg/source/mantisswap/pool_simulator.go, pkg/source/mantisswap/pool_tracker.go, pkg/source/mantisswap/pools_list_updater.go, pkg/source/mantisswap/type.go
=> Integrate: mantisswap (#181)

pkg/source/maverickv1/pool_simulator.go, pkg/source/maverickv1/type.go, pkg/source/wombat/wombatlsd/pool_simulator.go, pkg/source/wombat/wombatmain/pool_simulator.go
=> maverick: hiden swapInfo from API

pkg/source/gmx-glp/pool_simulator_helper.go, pkg/source/gmx-glp/pool_simulator_stake.go, pkg/source/gmx-glp/pool_simulator_unstake.go
=> fix: validate usdg

pkg/source/vooi/pool_simulator.go, pkg/source/vooi/pool_simulator_test.go
=> fix: wrong decimals on vooi

pkg/source/wombat/wombatlsd/errors.go, pkg/source/wombat/wombatlsd/math.go, pkg/source/wombat/wombatlsd/math_test.go, pkg/source/wombat/wombatlsd/pool_simulator.go, pkg/source/wombat/wombatmain/errors.go, pkg/source/wombat/wombatmain/math.go, pkg/source/wombat/wombatmain/math_test.go, pkg/source/wombat/wombatmain/pool_simulator.go
=> Wombat: validate wombat_forbbiden

pkg/source/maverickv1/pool_simulator.go
=> optimize: manual maverick deep clone

pkg/source/kyber-pmm/pool_simulator.go, pkg/source/kyber-pmm/type.go
=> chore: include timestamp in kyber-pmm meta info

pkg/source/pol-matic/constant.go, pkg/source/pol-matic/pool_list_updater.go, pkg/source/pol-matic/pool_simulator.go, pkg/source/pol-matic/pool_tracker.go
=> feat: add reserves of tokens for pol-matic

pkg/source/liquiditybookv21/parameters.go
=> fix: liquiditybook v2.1 safetype mul

pkg/source/kokonut-crypto/math.go
=> kokonut-crypto: return err when get newtonD

pkg/source/liquiditybookv21/pool_simulator.go, pkg/source/liquiditybookv21/pool_simulator_test.go, pkg/source/liquiditybookv21/type.go
=> fix: liquiditybookv21 return error when out of liquidity

pkg/source/wombat/pool_tracker.go, pkg/source/wombat/pools_list_updater.go
=> Wombat: support cross-chain-pool

go.mod, go.sum, pkg/source/kyber-pmm/pool_simulator.go
=> fix wrong comparision sign

pkg/source/fxdx/vault_scanner.go
=> chore: fxdx check pricefeed address before calling

pkg/source/kokonut-crypto/math.go
=> Fix bugs: return amount out is not enough

pkg/source/kyber-pmm/pool_tracker.go
=> clear PMM pool if no price returned

pkg/source/kyber-pmm/pool_tracker.go
=> clear PMM pool if no price returned (#229)

pkg/liquidity-source/velodrome-v1/pool_simulator.go, pkg/liquidity-source/velodrome-v1/pool_simulator_test.go, pkg/liquidity-source/velodrome-v2/pool_simulator.go, pkg/liquidity-source/velodrome-v2/pool_simulator_test.go
=> fix: velodrome-v1 and velodrome-v2 CalcAmountOutParams

pkg/liquidity-source/uniswap-v2/pool_simulator.go, pkg/source/smardex/pool_simulator.go, pkg/source/smardex/pool_simulator_test.go, pkg/source/smardex/type.go
=> chore: skip check uniswap-v2 and skip export smardex swapinfo

pkg/source/wombat/wombatlsd/math.go, pkg/source/wombat/wombatmain/math.go, pkg/source/wombat/wombatmain/math_test.go
=> fix: wombat WOMBAT_COV_RATIO_LIMIT_EXCEEDED

pkg/source/quickperps/errors.go, pkg/source/quickperps/pool_simulator_test.go
=> Fix quickperps testcase

pkg/source/maverickv1/constant.go, pkg/source/maverickv1/math.go, pkg/source/maverickv1/pool_simulator_test.go, pkg/source/quickperps/pool_simulator_test.go
=> improve: calcAmountOut maverick-v1

pkg/valueobject/exchange.go
https://team-kyber.atlassian.net/browse/AG-1254
=> chore: add uniswap-v2 to valueobject

pkg/source/wombat/wombatlsd/math.go, pkg/source/wombat/wombatlsd/pool_simulator.go, pkg/source/wombat/wombatlsd/pool_simulator_test.go, pkg/source/wombat/wombatmain/math.go, pkg/source/wombat/wombatmain/math_test.go, pkg/source/wombat/wombatmain/pool_simulator.go, pkg/source/wombat/wombatmain/pool_simulator_test.go
=> wombat: update balance

pkg/liquidity-source/balancer-v1/pools_list_updater.go
=> fix: balancer-v1 panic when there is no subgraph

pkg/liquidity-source/balancer-v1/pool_tracker.go
=> fix: balancer-v1 hex balance

pkg/source/liquiditybookv20/pool_simulator.go, pkg/source/liquiditybookv21/pool_simulator.go
- Do not panic when pools have no bins.
=> fix: liquidity book panic

pkg/source/fulcrom/abis.go, pkg/source/fulcrom/abis/ERC20.json, pkg/source/fulcrom/abis/Vault.json, pkg/source/fulcrom/abis/VaultPriceFeed.json, pkg/source/fulcrom/config.go, pkg/source/fulcrom/constants.go, pkg/source/fulcrom/embed.go, pkg/source/fulcrom/errors.go, pkg/source/fulcrom/helper.go, pkg/source/fulcrom/iface.go, pkg/source/fulcrom/pool_simulator.go, pkg/source/fulcrom/pool_tracker.go, pkg/source/fulcrom/pools_list_updater.go, pkg/source/fulcrom/types.go, pkg/source/fulcrom/usdg.go, pkg/source/fulcrom/usdg_reader.go, pkg/source/fulcrom/vault.go, pkg/source/fulcrom/vault_price_feed.go, pkg/source/fulcrom/vault_price_feed_reader.go, pkg/source/fulcrom/vault_reader.go, pkg/source/fulcrom/vault_scanner.go, pkg/source/fulcrom/vault_utils.go
=> Support fulcrom

pkg/source/wombat/wombatlsd/math.go, pkg/source/wombat/wombatlsd/math_test.go, pkg/source/wombat/wombatlsd/pool_simulator.go, pkg/source/wombat/wombatlsd/pool_simulator_test.go, pkg/source/wombat/wombatmain/math.go, pkg/source/wombat/wombatmain/math_test.go, pkg/source/wombat/wombatmain/pool_simulator.go, pkg/source/wombat/wombatmain/pool_simulator_test.go
=> Fix: wombat cov exceed and forbidden

pkg/source/maverickv1/config.go, pkg/source/maverickv1/constant.go, pkg/source/maverickv1/pool_tracker.go
=> Fix: maverick bugs, entity too large

pkg/liquidity-source/balancer-v1/b_num.go, pkg/liquidity-source/balancer-v1/b_numer_test.go, pkg/liquidity-source/balancer-v1/pools_list_updater.go
=> fix: balancer v1

pkg/source/vooi/pool_simulator.go, pkg/source/vooi/pool_simulator_test.go
=> Fix: vooi forbidden

pkg/source/pool/iface.go, pkg/source/uniswapv3/pool_simulator.go
=> support CalcAmountIn interface

pkg/liquidity-source/balancer-v1/pool_simulator.go, pkg/liquidity-source/balancer-v1/pool_simulator_test.go, pkg/liquidity-source/balancer-v2/composable-stable/config.go, pkg/liquidity-source/balancer-v2/composable-stable/constant.go, pkg/liquidity-source/balancer-v2/composable-stable/pool_simulator.go, pkg/liquidity-source/balancer-v2/composable-stable/pool_tracker.go, pkg/liquidity-source/balancer-v2/composable-stable/pools_list_updater.go, pkg/liquidity-source/balancer-v2/composable-stable/type.go, pkg/liquidity-source/balancer-v2/stable/config.go, pkg/liquidity-source/balancer-v2/stable/constant.go, pkg/liquidity-source/balancer-v2/stable/pool_simulator.go, pkg/liquidity-source/balancer-v2/stable/pool_tracker.go, pkg/liquidity-source/balancer-v2/stable/pools_list_updater.go, pkg/liquidity-source/balancer-v2/stable/type.go, pkg/liquidity-source/balancer-v2/weighted/config.go, pkg/liquidity-source/balancer-v2/weighted/constant.go, pkg/liquidity-source/balancer-v2/weighted/pool_simulator.go, pkg/liquidity-source/balancer-v2/weighted/pool_simulator_test.go, pkg/liquidity-source/balancer-v2/weighted/pool_tracker.go, pkg/liquidity-source/balancer-v2/weighted/pools_list_updater.go, pkg/liquidity-source/balancer-v2/weighted/type.go, pkg/liquidity-source/velocore-v2/cpmm/pool_simulator.go, pkg/liquidity-source/velocore-v2/cpmm/pool_tracker.go, pkg/liquidity-source/velocore-v2/cpmm/types.go, pkg/liquidity-source/velocore-v2/wombat-stable/pool_simulator.go, pkg/liquidity-source/velocore-v2/wombat-stable/pool_tracker.go, pkg/liquidity-source/velocore-v2/wombat-stable/type.go
=> refactor: balancer v1 v2 + velocore v2

pkg/liquidity-source/balancer-v2/weighted/pool_simulator.go
=> fix: balancer v2 weighted

go.mod, go.sum, pkg/source/uniswapv3/constant.go, pkg/source/uniswapv3/pool_simulator.go, pkg/source/uniswapv3/type.go
https://team-kyber.atlassian.net/browse/AG-113
=> AG-113: improve gas estimation for uniswap-v3

pkg/liquidity-source/balancer-v2/math/log_exp_math.go, pkg/liquidity-source/balancer-v2/math/log_exp_math_test.go, pkg/liquidity-source/balancer-v2/math/weighted_math_test.go, pkg/liquidity-source/balancer-v2/weighted/pool_simulator_test.go
=> fix: balancer v2

pkg/source/algebrav1/pool_tracker.go, pkg/source/algebrav1/type.go, pkg/source/pancakev3/pool_tracker.go, pkg/source/pancakev3/type.go, pkg/source/pool/iface.go, pkg/source/uniswapv3/pool_tracker.go, pkg/source/uniswapv3/type.go
=> refactor: expose function for ticks based tracker

go.mod, go.sum, pkg/source/algebrav1/pool_tracker.go, pkg/source/pancakev3/pool_tracker.go, pkg/source/uniswapv3/pool_tracker.go
=> refactor: store block number for ticks based dexes

pkg/source/solidly-v3/abis.go, pkg/source/solidly-v3/abis/ERC20.json, pkg/source/solidly-v3/abis/SolidlyV3Pool.json, pkg/source/solidly-v3/config.go, pkg/source/solidly-v3/constant.go, pkg/source/solidly-v3/embed.go, pkg/source/solidly-v3/math.go, pkg/source/solidly-v3/pool_simulator.go, pkg/source/solidly-v3/pool_tracker.go, pkg/source/solidly-v3/pools_list_updater.go, pkg/source/solidly-v3/queries.go, pkg/source/solidly-v3/type.go
=> feat: integrate solidly-v3

pkg/liquidity-source/uniswap-v2/pool_tracker.go
=> chore: add reserve data and block number to uniswap-v2 pool tracker log

pkg/liquidity-source/woofi-v2/pool_simulator.go, pkg/liquidity-source/woofi-v2/pool_simulator_test.go
https://team-kyber.slack.com/archives/C054H6WG7EV/p1703131024730139
=> fix: error in calculate basePrice1

pkg/liquidity-source/balancer-v2/composable-stable/pool_simulator.go, pkg/liquidity-source/balancer-v2/composable-stable/type.go, pkg/liquidity-source/balancer-v2/stable/pool_simulator.go, pkg/liquidity-source/balancer-v2/stable/type.go, pkg/liquidity-source/balancer-v2/weighted/pool_simulator.go, pkg/liquidity-source/balancer-v2/weighted/type.go
=> fix: balancer l2 encode

pkg/liquidity-source/balancer-v2/composable-stable/bpt_swap.go
=> fix: balancer composable stable panic

pkg/liquidity-source/woofi-v2/pool_simulator.go, pkg/liquidity-source/woofi-v2/pool_simulator_test.go
=> fix: woofi return underflow for reserve

.github/workflows/ci.yml, pkg/liquidity-source/balancer-v2/composable-stable/pool_simulator.go, pkg/liquidity-source/balancer-v2/composable-stable/pool_tracker.go, pkg/liquidity-source/balancer-v2/composable-stable/pools_list_updater.go, pkg/liquidity-source/balancer-v2/stable/constant.go, pkg/liquidity-source/balancer-v2/stable/error.go, pkg/liquidity-source/balancer-v2/stable/pool_list_updater_test.go, pkg/liquidity-source/balancer-v2/stable/pool_simulator.go, pkg/liquidity-source/balancer-v2/stable/pool_simulator_test.go, pkg/liquidity-source/balancer-v2/stable/pool_tracker.go, pkg/liquidity-source/balancer-v2/stable/pools_list_updater.go, pkg/liquidity-source/balancer-v2/stable/type.go, pkg/liquidity-source/balancer-v2/weighted/pool_simulator.go, pkg/liquidity-source/balancer-v2/weighted/pool_tracker.go, pkg/liquidity-source/balancer-v2/weighted/pools_list_updater.go
=> fix: balancer v2 stable

pkg/liquidity-source/woofi-v2/constant.go, pkg/liquidity-source/woofi-v2/pool_simulator.go, pkg/liquidity-source/woofi-v2/pool_simulator_test.go
=> fix: check compare nil address

pkg/source/dodo/pool_simulator.go, pkg/source/dodo/pool_simulator_test.go
=> fix dodo negative output (check reserves)

pkg/liquidity-source/velocore-v2/wombat-stable/pool_tracker.go
=> fix: velocore v2 wombat stable

pkg/source/maverickv1/math.go, pkg/source/maverickv1/pool_simulator_test.go
Benchmark:
Old code:
`BenchmarkNextActive-8   	    1539	    773825 ns/op	  906827 B/op	   29579 allocs/op`
New code:
`BenchmarkNextActive-8   	    2468	    487886 ns/op	  330530 B/op	   13581 allocs/op`
Load test in staging:
[Before](https://grafana.dev.kyberengineering.io/explore?panes=%7B%22Dnw%22:%7B%22datasource%22:%22be653393-82e3-419d-a7cc-45da32d9b139%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bhostname%3D%5C%22router-service-ethereum-api%5C%22%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22profileTypeId%22:%22process_cpu:cpu:nanoseconds:cpu:nanoseconds%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22be653393-82e3-419d-a7cc-45da32d9b139%22%7D%7D%5D,%22range%22:%7B%22from%22:%221704268800000%22,%22to%22:%22170426940 …
=> reduce alloc in maverick simulator

pkg/source/maverickv1/math.go, pkg/source/maverickv1/pool_simulator_test.go
* reduce alloc in maverick simulator
* fix lint
=> reduce alloc in maverick simulator (#287)

pkg/liquidity-source/uniswap-v2/log_decoder.go
=> fix: find correct latest log for uniswap-v2

pkg/source/maverickv1/constant.go, pkg/source/maverickv1/math.go
- constants are moved to `constant.go` to be initialized once instead of in every calls
- move `tick` variable in `tickPrice` func, and `nextWord` in `nextActive` func, to stack instead of heap (these funcs get called a lot, so a small optimization might still yield benefit)
Before: 
`BenchmarkNextActive-8   	    2481	    485163 ns/op	  330520 B/op	   13581 allocs/op`
After:
`BenchmarkNextActive-8   	    3831	    315069 ns/op	   59062 B/op	    5058 allocs/op`
Staging:
Before: [pyroscope](https://grafana.dev.kyberengineering.io/explore?panes=%7B%22Dnw%22:%7B%22datasource%22:%22be653393-82e3-419d-a7cc-45da32d9b139%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bservice_name%3D%5C%22router-service-ethereum-api%5C%22%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%2 …
=> reduce maverick alloc in loop (part 2)

pkg/source/curve/base/math.go, pkg/source/curve/base/pool_simulator.go, pkg/source/curve/base/pool_simulator_test.go
Before:
`BenchmarkCalcAmountOut-8   	  127633	      8462 ns/op	   10977 B/op	     219 allocs/op`
After:
`BenchmarkCalcAmountOut-8   	  172387	      6331 ns/op	    5380 B/op	     109 allocs/op`
Staging: CPU usage doesn't improved much, only memory alloc space
[Before](https://grafana.stg.kyberengineering.io/explore?panes=%7B%22xWS%22:%7B%22datasource%22:%22db1c2e86-663e-45e4-8240-da5e5eb7e53e%22,%22queries%22:%5B%7B%22groupBy%22:%5B%5D,%22labelSelector%22:%22%7Bhostname%3D%5C%22router-service-ethereum-api%5C%22,%20env%3D%5C%22staging%5C%22%7D%22,%22queryType%22:%22both%22,%22refId%22:%22A%22,%22profileTypeId%22:%22memory:alloc_space:bytes:space:bytes%22,%22datasource%22:%7B%22type%22:%22grafana-pyroscope-datasource%22,%22uid%22:%22db1c2e86-663e-45e4-8240-da5e5eb7e53e%22%7D%7D%5D,%22range%22 …
=> reduce alloc in curve base sim

pkg/source/curve/base/math.go
In the last PR (https://github.com/KyberNetwork/kyberswap-dex-lib/pull/294) there are some places where we use same destination as the argument into Mul and Div, for example `dP.Mul(&dP, &d)`
This will cause `dP` to be re-allocated again, because Mul and Div cannot calculate in-place (result still correct, but not optimized)
This PR will add some temporary variables to avoid that
New benchmark:
`BenchmarkCalcAmountOut-8   	  188505	      6077 ns/op	    4611 B/op	      97 allocs/op`
Benchmark from previous PR:
`BenchmarkCalcAmountOut-8   	  172387	      6331 ns/op	    5380 B/op	     109 allocs/op`
=> fix bigInt aliased in Mul/Div (over allocating)

pkg/source/curve/base/math.go, pkg/source/curve/base/pool_simulator.go, pkg/source/curve/base/pool_simulator_test.go, pkg/source/maverickv1/constant.go, pkg/source/maverickv1/math.go
=> reduce alloc in curve-base & maverick

pkg/source/maverickv1/errors.go, pkg/source/maverickv1/math.go, pkg/source/maverickv1/pool_simulator.go, pkg/source/maverickv1/pool_simulator_test.go
- Return error if pool doesn't have any bin
- Fix bin update
Paraswap code: https://github.com/paraswap/paraswap-dex-lib/blob/de2a6a2/src/dex/maverick-v1/maverick-math/maverick-pool-math.ts#L231
=> fix bin update for maverick

pkg/source/maverickv1/math.go, pkg/source/maverickv1/pool_simulator_test.go
=> fix maverick lsb and truncated div

pkg/source/maverickv1/errors.go, pkg/source/maverickv1/math.go, pkg/source/maverickv1/math_test.go, pkg/source/maverickv1/pool_simulator.go, pkg/source/maverickv1/pool_simulator_test.go, pkg/source/maverickv1/pool_tracker.go, pkg/source/maverickv1/type.go
=> maverick fix and improvement

pkg/source/smardex/pool_simulator.go
=> [Fix] smardex clone FeeToAmount instead of assigning to local variable

pkg/source/gmx-glp/pool_simulator.go, pkg/source/gmx-glp/pool_simulator_stake.go, pkg/source/gmx-glp/pool_simulator_unstake.go, pkg/source/gmx-glp/types.go, pkg/source/gmx-glp/vault.go, pkg/source/gmx-glp/yearn_token_vault.go
=> [Fix] gmx-gpl race condition (continue)

pkg/source/gmx-glp/pool_simulator.go, pkg/source/gmx-glp/pool_simulator_stake.go, pkg/source/gmx-glp/pool_simulator_unstake.go, pkg/source/gmx-glp/types.go, pkg/source/gmx-glp/vault.go, pkg/source/gmx-glp/yearn_token_vault.go, pkg/source/smardex/pool_simulator.go
=> Fixes to apply to release-v0.27

pkg/liquidity-source/balancer-v1/pool_simulator_test.go, pkg/liquidity-source/balancer-v2/composable-stable/pool_simulator_test.go, pkg/liquidity-source/balancer-v2/stable/pool_simulator_test.go, pkg/liquidity-source/balancer-v2/weighted/pool_simulator_test.go, pkg/liquidity-source/uniswap-v2/pool_simulator_test.go, pkg/liquidity-source/velocore-v2/cpmm/pool_simulartor_test.go, pkg/liquidity-source/velocore-v2/wombat-stable/pool_simulator_test.go, pkg/liquidity-source/velodrome-v1/pool_simulator_test.go, pkg/liquidity-source/velodrome-v2/pool_simulator_test.go, pkg/liquidity-source/woofi-v2/pool_simulator_test.go
=> Add tests in pkg/liquidity-sources to check if CalcAmountOut() is concurrent safe

pkg/valueobject/exchange.go
=> chore: add exchange valueobject gyroscope

pkg/liquidity-source/gyroscope/eclp/pool_tracker.go
=> fix: gyroscope eclp

pkg/liquidity-source/swaap-v2/constant.go, pkg/liquidity-source/swaap-v2/inventory.go, pkg/liquidity-source/swaap-v2/pool_simulator.go, pkg/liquidity-source/swaap-v2/pool_simulator_test.go, pkg/pooltypes/pooltypes.go, pkg/valueobject/exchange.go
=> feat: support swaap-v2

pkg/valueobject/exchange.go
=> feat: support pharaoh

pkg/valueobject/exchange.go
=> fix: rename pharaoh to pharaoh-v2

pkg/source/velodrome/pool_tracker.go, pkg/valueobject/exchange.go
=> feat: add exchange nile, nile-v2

pkg/valueobject/exchange.go
=> feat: integrate pharaoh

pkg/liquidity-source/swaap-v2/client/config.go, pkg/liquidity-source/swaap-v2/client/http.go, pkg/liquidity-source/swaap-v2/client/type.go, pkg/liquidity-source/swaap-v2/constant.go, pkg/liquidity-source/swaap-v2/pool_simulator.go, pkg/liquidity-source/swaap-v2/rfq.go, pkg/source/kyber-pmm/rfq.go, pkg/source/limitorder/rfq.go, pkg/source/pool/iface.go, pkg/source/pool/rfq.go
=> feat: Swaap V2

pkg/valueobject/exchange.go
=> feat: integrate blueprint

pkg/liquidity-source/velodrome-v2/pool_simulator_test.go, pkg/source/algebrav1/pool_simulator_test.go, pkg/source/pool/iface.go, pkg/source/pool/pool.go, pkg/source/uniswapv3/pool_simulator.go
=> add ApproxAmountIn method

pkg/valueobject/exchange.go
=> feat: integrate nuri & nuri-v2

go.mod, go.sum, pkg/liquidity-source/bancor-v3/abis.go, pkg/liquidity-source/bancor-v3/abis/BancorNetwork.json, pkg/liquidity-source/bancor-v3/abis/PoolCollection.json, pkg/liquidity-source/bancor-v3/config.go, pkg/liquidity-source/bancor-v3/constant.go, pkg/liquidity-source/bancor-v3/embed.go, pkg/liquidity-source/bancor-v3/error.go, pkg/liquidity-source/bancor-v3/math/math_ex.go, pkg/liquidity-source/bancor-v3/pool_collection.go, pkg/liquidity-source/bancor-v3/pool_simulator.go, pkg/liquidity-source/bancor-v3/pool_simulator_test.go, pkg/liquidity-source/bancor-v3/pool_tracker.go, pkg/liquidity-source/bancor-v3/pools_list_updater.go, pkg/liquidity-source/bancor-v3/type.go, pkg/valueobject/exchange.go
=> feat: bancor v3

pkg/liquidity-source/uniswap-v2/pool_simulator.go, pkg/liquidity-source/uniswap-v2/pool_simulator_test.go
=> feat: calcAmountIn for uniswap-v2

go.mod, go.sum, pkg/source/pool/pool.go, pkg/source/uniswapv3/pool_simulator.go
=> returning AmountIn

pkg/liquidity-source/etherfi/weeth/pool_simulator.go
=> feat: add update balance to weeth

pkg/pooltypes/pooltypes.go, pkg/valueobject/exchange.go
=> add constants for some new pool types

pkg/valueobject/exchange.go
=> add zkera finance to AMMSourceSet

pkg/source/curve/pools_list_updater.go
=> ignore missing hardcoded pool

pkg/liquidity-source/bancor-v3/pool_simulator.go, pkg/liquidity-source/bancor-v3/pool_tracker.go, pkg/liquidity-source/bancor-v3/pools_list_updater.go, pkg/liquidity-source/ethena/susde/abis.go, pkg/liquidity-source/ethena/susde/abis/StakedUSDeV2.json, pkg/liquidity-source/ethena/susde/config.go, pkg/liquidity-source/ethena/susde/constant.go, pkg/liquidity-source/ethena/susde/embed.go, pkg/liquidity-source/ethena/susde/pool_simulator.go, pkg/liquidity-source/ethena/susde/pool_tracker.go, pkg/liquidity-source/ethena/susde/pools_list_updater.go, pkg/pooltypes/pooltypes.go, pkg/valueobject/exchange.go
=> feat: ethena susde

pkg/liquidity-source/rocketpool/reth/pool_list_updater.go, pkg/liquidity-source/rocketpool/reth/pool_simulator.go
=> fix: rocketpool correct update balance & calculate maximum

pkg/liquidity-source/maker/savingsdai/abis.go, pkg/liquidity-source/maker/savingsdai/abis/Pot.json, pkg/liquidity-source/maker/savingsdai/abis/SavingsDai.json, pkg/liquidity-source/maker/savingsdai/constant.go, pkg/liquidity-source/maker/savingsdai/embed.go, pkg/liquidity-source/maker/savingsdai/math.go, pkg/liquidity-source/maker/savingsdai/pool_simulator.go, pkg/liquidity-source/maker/savingsdai/pool_tracker.go, pkg/liquidity-source/maker/savingsdai/pools_list_updater.go, pkg/liquidity-source/maker/savingsdai/types.go, pkg/liquidity-source/velocore-v2/cpmm/pools_list_updater.go, pkg/pooltypes/pooltypes.go, pkg/valueobject/exchange.go
=> feat: maker savingsdai

pkg/liquidity-source/curve/plain/pool_simulator.go, pkg/liquidity-source/curve/plain/pools_list_updater.go, pkg/liquidity-source/curve/plain/type.go, pkg/liquidity-source/curve/shared/pools_list_updater.go, pkg/liquidity-source/curve/shared/type.go, pkg/source/curve/type.go
=> track native coin before converting to wrapped

pkg/liquidity-source/curve/plain/abis.go, pkg/liquidity-source/curve/plain/pool_tracker.go
=> support old ABI for curve pool

go.mod, go.sum, pkg/liquidity-source/curve/plain/math.go, pkg/liquidity-source/curve/plain/pool_simulator_test.go
=> use safemath for curve-stable-plain

go.mod, go.sum, pkg/liquidity-source/curve/stable-ng/math.go, pkg/liquidity-source/curve/stable-ng/pool_simulator.go, pkg/liquidity-source/curve/stable-ng/pool_simulator_test.go
=> curve-stable-ng: pool simulator

go.mod, go.sum, pkg/liquidity-source/curve/stable-ng/math.go, pkg/liquidity-source/curve/stable-ng/pool_simulator.go, pkg/liquidity-source/curve/stable-ng/pool_simulator_test.go, pkg/liquidity-source/curve/stable-ng/pool_tracker.go
=> curve-stable-ng: pool tracker

pkg/pooltypes/pooltypes.go, pkg/valueobject/exchange.go
=> add pool/exchange type for curve-stable-ng

.github/workflows/ci.yml, pkg/liquidity-source/swaap-v2/constant.go, pkg/liquidity-source/swaap-v2/pool_simulator.go, pkg/liquidity-source/swaap-v2/pool_simulator_test.go
=> fix: swaap-v2

pkg/source/saddle/pools/synapse/blast.json
=> feat: support synapse on blast

pkg/source/saddle/embed.go
=> fix: register synapse blast pool in saddle

pkg/valueobject/exchange.go
=> chore: add exchanges on Blast

pkg/valueobject/exchange.go
=> feat: add exchanges on Blast

pkg/source/solidly-v3/pool_tracker.go, pkg/source/solidly-v3/type.go
=> feat: expose solidlyv3 to integrate with ticks-based-worker

pkg/liquidity-source/curve/plain/pool_tracker.go
=> fix curve plain registry rates

pkg/source/ramsesv2/pool_tracker.go, pkg/source/ramsesv2/type.go
=> feat: expose ramses-v2 for ticks-based-worker

pkg/liquidity-source/curve/stable-ng/pool_tracker.go
=> ignore invalid rates for curve stable ng

pkg/valueobject/exchange.go
=> chore: add exchange Equal & Equalizer CL

pkg/liquidity-source/curve/stable-meta-ng/pool_tracker.go
=> curve-stable-meta-ng: pool tracker

pkg/liquidity-source/curve/plain/math.go, pkg/liquidity-source/curve/plain/pool_simulator_basepool_test.go, pkg/liquidity-source/curve/stable-ng/math.go, pkg/liquidity-source/curve/stable-ng/pool_simulator.go
=> curve-stable-meta-ng: update plain/stable-ng to become base pool

pkg/liquidity-source/curve/stable-meta-ng/constant.go, pkg/liquidity-source/curve/stable-meta-ng/math.go, pkg/liquidity-source/curve/stable-meta-ng/pool_simulator.go
=> curve-stable-meta-ng: simulator

pkg/liquidity-source/curve/stable-meta-ng/benchmark_test.go, pkg/liquidity-source/curve/stable-meta-ng/pool_simulator_test.go
=> curve-stable-meta-ng: simulator test

pkg/valueobject/exchange.go
=> set AMM for cuve-stable-meta-ng

pkg/source/liquiditybookv20/bin.go, pkg/source/liquiditybookv20/helper.go, pkg/source/liquiditybookv20/pool_simulator.go, pkg/source/liquiditybookv20/pool_tracker.go, pkg/source/liquiditybookv20/type.go, pkg/source/liquiditybookv21/bin.go, pkg/source/liquiditybookv21/helper.go, pkg/source/liquiditybookv21/pool_simulator.go, pkg/source/liquiditybookv21/pool_tracker.go, pkg/source/liquiditybookv21/type.go
=> feat: integrate liquiditybook to ticksbased

pkg/liquidity-source/swaap-v2/pool_simulator.go
=> chore: change tokens ptr to values in swaapv2

pkg/source/velodrome/pools_list_updater.go
=> feat: ignore error pool in velodrome

pkg/valueobject/exchange.go
=> feat: integrate Lynex V1 and Skydrome V2

pkg/source/liquiditybookv20/bin.go, pkg/source/liquiditybookv20/helper.go, pkg/source/liquiditybookv20/pool_simulator.go, pkg/source/liquiditybookv21/bin.go, pkg/source/liquiditybookv21/helper.go, pkg/source/liquiditybookv21/pool_simulator.go
=> fix: remove total supply in LB bins 

pkg/liquidity-source/hashflow-v3/client/config.go, pkg/liquidity-source/hashflow-v3/client/http.go, pkg/liquidity-source/hashflow-v3/constant.go, pkg/liquidity-source/hashflow-v3/pool_simulator.go, pkg/liquidity-source/hashflow-v3/pool_simulator_test.go, pkg/liquidity-source/hashflow-v3/rfq.go, pkg/liquidity-source/hashflow-v3/type.go, pkg/pooltypes/pooltypes.go, pkg/valueobject/exchange.go
=> EX-1117: integrate hashflow-v3

pkg/valueobject/exchange.go
=> feat: integrate squadswap

pkg/liquidity-source/curve/tricrypto-ng/pool_tracker.go
=> curve tricrypto-ng: pool tracker

pkg/liquidity-source/curve/tricrypto-ng/math_test.go, pkg/liquidity-source/curve/tricrypto-ng/pool_simulator_test.go
=> curve tricrypto-ng: pool simulator test

pkg/liquidity-source/curve/tricrypto-ng/curve_tricrypto_optimized_weth.go, pkg/liquidity-source/curve/tricrypto-ng/math.go, pkg/liquidity-source/curve/tricrypto-ng/math_test.go, pkg/liquidity-source/curve/tricrypto-ng/pool_simulator.go, pkg/liquidity-source/curve/tricrypto-ng/pool_simulator_test.go
=> curve tricrypto-ng: pool simulator

pkg/liquidity-source/hashflow-v3/client/http.go
=> chore: return custom err for hashflow rfq

go.mod, go.sum, pkg/source/pool/pool.go, pkg/source/uniswapv3/pool_simulator_bigint.go, pkg/source/uniswapv3/pool_simulator_bigint_test.go
=> refactor: return remaining amount out when calculate amount in

pkg/liquidity-source/hashflow-v3/client/http.go
=> chore (hashflow): support market too volatile message

go.mod, go.sum, pkg/source/pancakev3/constant.go, pkg/source/pancakev3/pool_simulator.go, pkg/source/pancakev3/pool_simulator_test.go, pkg/source/pancakev3/type.go, pkg/source/uniswapv3/pool_simulator_bigint_test.go
=> refactor: implement pancake-v3 CalcAmountIn

pkg/source/fraxswap/pool_simulator.go, pkg/source/fraxswap/pool_tracker.go
=> fix fraxswap nil reserves

pkg/liquidity-source/balancer-v2/math/weighted_math.go, pkg/liquidity-source/balancer-v2/math/weighted_math_test.go, pkg/liquidity-source/balancer-v2/weighted/pool_simulator.go, pkg/liquidity-source/balancer-v2/weighted/pool_simulator_test.go
Add CalcAmountIn to support get sell price in https://github.com/kybernetwork/onchain-price-service
This might also benefit the router-service later when we decide to support exact out simulation
=> feat: implement balancer weighted calc amount in

pkg/liquidity-source/balancer-v2/math/stable_math.go, pkg/liquidity-source/balancer-v2/math/stable_math_test.go, pkg/liquidity-source/balancer-v2/stable/error.go, pkg/liquidity-source/balancer-v2/stable/pool_simulator.go, pkg/liquidity-source/balancer-v2/stable/pool_simulator_test.go, pkg/liquidity-source/balancer-v2/weighted/pool_simulator.go
=> feat: implement CalcAmountIn for balancer-v2-stable

pkg/liquidity-source/balancer-v2/composable-stable/bpt_swap.go, pkg/liquidity-source/balancer-v2/composable-stable/pool_simulator.go, pkg/liquidity-source/balancer-v2/composable-stable/pool_simulator_test.go, pkg/liquidity-source/balancer-v2/composable-stable/regular_swap.go, pkg/liquidity-source/balancer-v2/math/stable_math.go
=> feat: implement CalcAmountIn for balancer-v2-composable-stable

pkg/source/kyber-pmm/pool_simulator.go
=> fix update balance kyber-pmm

pkg/liquidity-source/rocketpool/reth/pool_simulator.go
=> remove printf rocketpool

pkg/liquidity-source/native-v1/client/http.go, pkg/liquidity-source/native-v1/type.go
- per updated sc logic, we will directly use calldata in the response instead of building it ourselves
=> feat: simplify native rfq call

pkg/liquidity-source/bancor-v3/pool_collection.go, pkg/liquidity-source/bancor-v3/pool_simulator.go, pkg/liquidity-source/bancor-v3/pool_simulator_test.go
=> feat: implement CalcAmountIn for bancor-v3

pkg/liquidity-source/bedrock/unieth/constant.go, pkg/liquidity-source/bedrock/unieth/pool_simulator.go, pkg/liquidity-source/puffer/pufeth/pool_simulator.go, pkg/liquidity-source/puffer/pufeth/types.go
=> chore: add necessary swell encoding data

pkg/source/solidly-v3/pool_simulator.go, pkg/source/solidly-v3/pool_simulator_test.go
=> feat: implement CalcAmountIn for solidly-v3

pkg/valueobject/exchange.go
=> feat: integrate degen-express

Makefile, pkg/source/maverickv1/math.go, pkg/source/maverickv1/math_test.go, pkg/source/maverickv1/pool_simulator.go, pkg/source/maverickv1/pool_simulator_test.go
=> feat: implement CalcAmountIn for maverick-v1

pkg/source/curve/pools/pancake-stable/arbitrum.json, pkg/source/curve/pools/pancake-stable/bsc.json
=> feat: add pendle/mpendle pancake stable pair

pkg/source/pancakev3/constant.go, pkg/source/pancakev3/pool_simulator.go, pkg/source/pancakev3/pool_tracker.go, pkg/source/pancakev3/type.go, pkg/source/uniswapv3/constant.go, pkg/source/uniswapv3/pool_simulator.go, pkg/source/uniswapv3/pool_simulator_bigint.go, pkg/source/uniswapv3/pool_tracker.go, pkg/source/uniswapv3/type.go
=> feat: save tick spacing to extra

pkg/source/maverickv1/math.go, pkg/source/maverickv1/pool_simulator.go
=> chore (maverick-v1): expose scale to amount

pkg/source/syncswap/syncswapclassic/math.go, pkg/source/syncswap/syncswapclassic/pool_simulator.go, pkg/source/syncswap/syncswapclassic/pool_simulator_test.go
=> feat: implement CalcAmountIn for syncswap-classic

pkg/liquidity-source/hashflow-v3/type.go
=> chore: add json tag for quote data

pkg/source/syncswap/syncswapclassic/pool_simulator.go, pkg/source/syncswap/syncswapstable/math.go, pkg/source/syncswap/syncswapstable/pool_simulator.go, pkg/source/syncswap/syncswapstable/pool_simulator_test.go
=> feat: implement CalcAmountIn for syncswap-stable

pkg/liquidity-source/hashflow-v3/type.go, pkg/source/curve/embed.go
=> feat: integrate pancake-stable on arbitrum

pkg/source/limitorder/http_client_dto.go, pkg/source/limitorder/pool_simulator.go, pkg/source/limitorder/pool_simulator_test.go
=> use limit-order AvailableMakingAmount

pkg/liquidity-source/curve/plain/constant.go, pkg/liquidity-source/curve/plain/math.go, pkg/liquidity-source/curve/plain/pool_simulator.go, pkg/liquidity-source/curve/plain/pool_simulator_test.go
=> feat: implement curve plain calc amount in

pkg/source/limitorder/config.go, pkg/source/limitorder/http_client.go, pkg/source/limitorder/http_client_dto.go, pkg/source/limitorder/pool_tracker.go
=> add flag includeInsufficientBalance when calling LO

pkg/valueobject/exchange.go
=> feat: support new xlayer dex

pkg/liquidity-source/curve/stable-ng/constant.go, pkg/liquidity-source/curve/stable-ng/math.go, pkg/liquidity-source/curve/stable-ng/pool_simulator.go, pkg/liquidity-source/curve/stable-ng/pool_simulator_test.go
https://team-kyber.atlassian.net/browse/EX-1607
=> feat: calc amount in for curve-stable-ng

pkg/pooltypes/pooltypes.go, pkg/source/slipstream/abis.go, pkg/source/slipstream/abis/ERC20.json, pkg/source/slipstream/abis/Pool.json, pkg/source/slipstream/config.go, pkg/source/slipstream/constant.go, pkg/source/slipstream/embed.go, pkg/source/slipstream/math.go, pkg/source/slipstream/pool_simulator.go, pkg/source/slipstream/pool_simulator_bigint.go, pkg/source/slipstream/pool_tracker.go, pkg/source/slipstream/pools_list_updater.go, pkg/source/slipstream/queries.go, pkg/source/slipstream/type.go, pkg/valueobject/exchange.go
=> feat: integrate slipstream

pkg/liquidity-source/curve/tricrypto-ng/constant.go, pkg/liquidity-source/curve/tricrypto-ng/curve_tricrypto_optimized_weth.go, pkg/liquidity-source/curve/tricrypto-ng/pool_simulator.go, pkg/liquidity-source/curve/tricrypto-ng/pool_simulator_test.go
https://team-kyber.atlassian.net/browse/EX-1615
=> feat: calc amount in for curve tricrypto-ng

pkg/valueobject/exchange.go
=> feat: add new exchanges linehub & wigo

pkg/source/limitorder/http_client_dto.go, pkg/source/limitorder/pool_simulator.go, pkg/source/limitorder/pool_simulator_test.go
=> track inventory limit for limit-order

pkg/source/limitorder/pool_simulator.go
=> remove type alias makerAndAsset (issue with goclone)

go.mod, go.sum, pkg/source/iziswap/pool_simulator.go, pkg/source/iziswap/pool_simulator_test.go, pkg/source/iziswap/pool_tracker.go, pkg/source/iziswap/snapshot.go, pkg/source/iziswap/type.go
https://team-kyber.atlassian.net/browse/EX-1520
=> feat: implement CalcAmountIn for iziswap

pkg/valueobject/exchange.go
=> feat: integrate infusion, soswap (base) & uniswap (blast)

pkg/source/iziswap/pool_simulator.go, pkg/source/iziswap/pool_simulator_test.go
https://team-kyber.atlassian.net/browse/EX-1520
=> fix: return the remaining amount out (partial fill) for iziswap

pkg/valueobject/exchange.go
=> feat: add new exchanges

pkg/liquidity-source/curve/plain/math.go, pkg/liquidity-source/curve/plain/pool_simulator.go, pkg/liquidity-source/curve/plain/pool_simulator_test.go, pkg/liquidity-source/curve/stable-ng/pool_simulator.go, pkg/liquidity-source/curve/tricrypto-ng/pool_simulator.go
https://team-kyber.slack.com/archives/C03LF2EK6NB/p1716780899312209?thread_ts=1712111542.336119&cid=C03LF2EK6NB
=> fix: curve stable plain CalcAmountIn

pkg/liquidity-source/woofi-v2/config.go, pkg/valueobject/exchange.go
=> feat: integrate woofi-v3

pkg/source/maverickv1/constant.go
=> improve: reduce chunk size when fetch bins

pkg/valueobject/exchange.go
=> feat: add new exchanges alien-base-degen, koi-cl, tokan & secta

pkg/liquidity-source/dodo/classical/constant.go, pkg/liquidity-source/dodo/classical/error.go, pkg/liquidity-source/dodo/classical/pool_simulator.go, pkg/liquidity-source/dodo/classical/pool_simulator_test.go, pkg/liquidity-source/dodo/classical/sell_helper.go, pkg/liquidity-source/dodo/classical/type.go
Support sell quote for dodo-classical
=> fix: support dodo-classical sell quote

pkg/liquidity-source/velodrome-v1/pool_simulator.go, pkg/liquidity-source/velodrome-v1/pool_simulator_test.go, pkg/liquidity-source/velodrome-v1/safe_math.go, pkg/liquidity-source/velodrome-v2/pool_simulator.go, pkg/liquidity-source/velodrome-v2/pool_simulator_test.go, pkg/liquidity-source/velodrome-v2/safe_math.go
https://team-kyber.atlassian.net/browse/EX-1650
=> feat: implement CalcAmountIn for velodrome + velodrome-v2 volatile

pkg/liquidity-source/dodo/classical/error.go, pkg/liquidity-source/dodo/classical/pool_simulator.go, pkg/liquidity-source/dodo/classical/pool_simulator_test.go, pkg/liquidity-source/dodo/classical/type.go, pkg/liquidity-source/dodo/shared/constant.go, pkg/liquidity-source/dodo/shared/pool_tracker.go, pkg/liquidity-source/dodo/shared/type.go
=> fix: take into account dodo-classical check TRADE_NOT_ALLOWED

pkg/liquidity-source/velodrome-v1/pool_simulator.go, pkg/liquidity-source/velodrome-v1/pool_simulator_test.go
=> fix: velodrome-v1 CalcAmountOut

pkg/liquidity-source/velodrome-v1/pool_list_updater.go
=> fix: velodrome-v1 list metadata

pkg/source/liquiditybookv20/pool_tracker.go, pkg/source/liquiditybookv21/pool_tracker.go, pkg/source/wombat/pool_tracker.go
=> fix: fix panic issue when calling subgraph

pkg/liquidity-source/velodrome-v1/fee_tracker.go
=> fix: update fee data type for velodrome

pkg/source/syncswap/syncswapclassic/pool_simulator.go, pkg/source/syncswap/syncswapclassic/pool_simulator_test.go
=> fix: syncswap update balance

pkg/source/limitorder/errors.go, pkg/source/limitorder/rfq.go
=> reject swap if recipient==receiver

pkg/pooltypes/pooltypes.go, pkg/source/nuriv2/abis.go, pkg/source/nuriv2/abis/ERC20.json, pkg/source/nuriv2/abis/NuriV2Pool.json, pkg/source/nuriv2/config.go, pkg/source/nuriv2/constant.go, pkg/source/nuriv2/embed.go, pkg/source/nuriv2/math.go, pkg/source/nuriv2/pool_simulator.go, pkg/source/nuriv2/pool_simulator_test.go, pkg/source/nuriv2/pool_tracker.go, pkg/source/nuriv2/pools_list_updater.go, pkg/source/nuriv2/queries.go, pkg/source/nuriv2/type.go
=> fix: update nuri-v2 dex integration

pkg/msgpack/register_pool_types.go
=> chore: update go generate

pkg/source/algebrav1/pool_tracker.go, pkg/source/liquiditybookv20/abis.go, pkg/source/liquiditybookv20/abis/LBRouter.json, pkg/source/liquiditybookv20/config.go, pkg/source/liquiditybookv20/constant.go, pkg/source/liquiditybookv20/embed.go, pkg/source/liquiditybookv20/pool_tracker.go, pkg/source/liquiditybookv20/type.go, pkg/source/liquiditybookv21/constant.go, pkg/source/liquiditybookv21/pool_tracker.go, pkg/source/liquiditybookv21/type.go, pkg/source/nuriv2/pool_tracker.go, pkg/source/pancakev3/pool_tracker.go, pkg/source/pool/iface.go, pkg/source/ramsesv2/pool_tracker.go, pkg/source/slipstream/pool_tracker.go, pkg/source/solidly-v3/pool_tracker.go, pkg/source/uniswapv3/pool_tracker.go
=> EX-1714: fetch RPC with block number param

pkg/valueobject/exchange.go
=> [fix] Add ExchangeAmbient to valueobject package

pkg/valueobject/exchange.go
=> EX-1855: integrate velodrome-cl-2

pkg/liquidity-source/ambient/config.go, pkg/liquidity-source/ambient/constants.go, pkg/liquidity-source/ambient/iface.go, pkg/liquidity-source/ambient/pool_list_updater.go, pkg/liquidity-source/ambient/pool_list_updater_test.go, pkg/liquidity-source/ambient/pool_tracker.go, pkg/liquidity-source/ambient/pool_tracker_test.go, pkg/liquidity-source/ambient/types.go, pkg/liquidity-source/ambient/types_test.go
=> cherry pick ambient refactor to `release-v0.60`

pkg/source/pool/pool.go
This log is messy and causes grafana loki slowly responses
https://grafana.kyberengineering.io/explore?schemaVersion=1&panes=%7B%22hyg%22:%7B%22datasource%22:%22fdihtl8cgsg00c%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bdeployment%3D~%5C%22router-service-ethereum-api%5C%22%7D%20%7C%3D%20%5C%22panic%5C%22%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22fdihtl8cgsg00c%22%7D,%22editorMode%22:%22code%22%7D%5D,%22range%22:%7B%22from%22:%22now-15m%22,%22to%22:%22now%22%7D%7D%7D&orgId=1
=> Remove messy log

pkg/liquidity-source/ambient/types.go
=> Cherry pick "implement missing CanSwapFrom for ambient.NTokenPool (#495)" to release-v0.61

pkg/source/limitorder/pool_simulator.go, pkg/source/limitorder/pool_simulator_test.go
https://team-kyber.atlassian.net/browse/EX-2024
=> fix bug LO too small

pkg/liquidity-source/dodo/dpp/pool_simulator.go, pkg/liquidity-source/dodo/dpp/storage.go, pkg/liquidity-source/dodo/dsp/pool_simulator.go, pkg/liquidity-source/dodo/dsp/storage.go, pkg/liquidity-source/dodo/dvm/pool_simulator.go, pkg/liquidity-source/dodo/dvm/storage.go
=> fix: dodo v2 pool panic when cloning

CODEOWNERS
=> add Phu as CODEOWNERS

pkg/liquidity-source/maverick-v2/abis.go, pkg/liquidity-source/maverick-v2/abis/MaverickV2Factory.json, pkg/liquidity-source/maverick-v2/abis/MaverickV2Pool.json, pkg/liquidity-source/maverick-v2/config.go, pkg/liquidity-source/maverick-v2/constant.go, pkg/liquidity-source/maverick-v2/embed.go, pkg/liquidity-source/maverick-v2/pool_list_updater.go, pkg/liquidity-source/maverick-v2/pool_tracker.go, pkg/liquidity-source/maverick-v2/types.go, pkg/valueobject/exchange.go
=> feat: integrate maverick-v2 for tracking pools

pkg/liquidity-source/litepsm/abis.go, pkg/liquidity-source/litepsm/abis/ERC20.json, pkg/liquidity-source/litepsm/abis/LitePSM.json, pkg/liquidity-source/litepsm/config.go, pkg/liquidity-source/litepsm/constant.go, pkg/liquidity-source/litepsm/dexconfig/ethereum.json, pkg/liquidity-source/litepsm/embed.go, pkg/liquidity-source/litepsm/errors.go, pkg/liquidity-source/litepsm/litepsm.go, pkg/liquidity-source/litepsm/pool_simulator.go, pkg/liquidity-source/litepsm/pool_tracker.go, pkg/liquidity-source/litepsm/pools_list_updater.go, pkg/liquidity-source/litepsm/type.go, pkg/msgpack/register_pool_types.go, pkg/valueobject/exchange.go
=> feat: integrate lite-psm

pkg/liquidity-source/integral/constant.go, pkg/liquidity-source/integral/pool_list_updater_test.go, pkg/liquidity-source/integral/pool_simulator.go, pkg/liquidity-source/integral/pool_simulator_test.go, pkg/liquidity-source/integral/pool_tracker.go, pkg/liquidity-source/integral/pool_tracker_test.go, pkg/liquidity-source/integral/type.go
=> fix(Integral): Add logic check limit tokenOut max

pkg/liquidity-source/integral/pool_tracker.go
=> fix(integral) : add check if pool is disabled

pkg/source/makerpsm/pool_tracker.go, pkg/source/makerpsm/psm_reader.go, pkg/source/makerpsm/vat_reader.go
=> feat: maker psm stateoverrides

.github/workflows/release.yaml
=> chore: update release CI runs on github runner

pkg/liquidity-source/fluid/vault-t1/config.go, pkg/liquidity-source/fluid/vault-t1/pool_simulator.go, pkg/liquidity-source/fluid/vault-t1/pool_simulator_test.go
=> fix : Add check available reserve and adjust default gas

pkg/liquidity-source/hashflow-v3/rfq.go
=> feat: support exclude market makers on hashflow-v3

pkg/liquidity-source/usd0pp/pool_tracker.go
=> feat: usd0pp state overrides

pkg/liquidity-source/fluid/vault-t1/pool_tracker.go
=> feat: fluid t1 state overrides

pkg/liquidity-source/bebop/client/http.go, pkg/liquidity-source/bebop/pool_simulator_test.go
- Fix bebop get quote Headers
- Using the wrong headers
- https://api.bebop.xyz/pmm/ethereum/docs#/v3/quote_v3_quote_get
=> refactor: ♻️ bebop: fix header & add entity test

pkg/liquidity-source/generic-simple-rate/utils.go, pkg/liquidity-source/oeth/embed.go, pkg/liquidity-source/oeth/pools/ethereum.json, pkg/liquidity-source/wbeth/abis.go, pkg/liquidity-source/wbeth/abis/wBETH.json, pkg/liquidity-source/wbeth/embed.go, pkg/liquidity-source/wbeth/pools/bsc.json, pkg/liquidity-source/wbeth/pools/ethereum.json, pkg/valueobject/exchange.go
=> feat: integrate wbeth and oeth

pkg/liquidity-source/bebop/pool_simulator.go
=> fix: 🩹 bebop: nil check SwapLimits

pkg/liquidity-source/frax/frxeth/embed.go, pkg/liquidity-source/frax/frxeth/pools/ethereum.json, pkg/liquidity-source/generic-simple-rate/utils.go, pkg/valueobject/exchange.go
=> feat: integrate frxeth

pkg/liquidity-source/uniswap-v1/abis.go, pkg/liquidity-source/uniswap-v1/abis/ERC20.json, pkg/liquidity-source/uniswap-v1/abis/multicall.json, pkg/liquidity-source/uniswap-v1/abis/uniswap_exchange.json, pkg/liquidity-source/uniswap-v1/abis/uniswap_factory.json, pkg/liquidity-source/uniswap-v1/config.go, pkg/liquidity-source/uniswap-v1/constant.go, pkg/liquidity-source/uniswap-v1/embed.go, pkg/liquidity-source/uniswap-v1/pool_list_updater.go, pkg/liquidity-source/uniswap-v1/pool_simulator.go, pkg/liquidity-source/uniswap-v1/pool_simulator_test.go, pkg/liquidity-source/uniswap-v1/pool_tracker.go, pkg/liquidity-source/uniswap-v1/types.go, pkg/msgpack/register_pool_types.go, pkg/pooltypes/pooltypes.go, pkg/valueobject/exchange.go
=> feat : Implement Uniswap-v1 

pkg/liquidity-source/curve/stable-meta-ng/pool_simulator.go
=> expose curve meta-ng base pool

pkg/liquidity-source/uniswap-v1/pool_tracker.go
=> feat: univ1 state overrides

pkg/source/uniswapv3/config.go, pkg/source/uniswapv3/pool_tracker.go
=> univ3 to support always using ticklens instead of subgraph

pkg/liquidity-source/uniswap-v2/pool_simulator.go
=> fix: CalcAmountIn uniswap-v2 wrong index of tokenIn

pkg/liquidity-source/clipper/client/http.go, pkg/liquidity-source/clipper/config.go, pkg/liquidity-source/clipper/constant.go, pkg/liquidity-source/clipper/pool_simulator.go, pkg/liquidity-source/clipper/pool_simulator_test.go, pkg/liquidity-source/clipper/rfq.go, pkg/liquidity-source/clipper/type.go, pkg/msgpack/register_pool_types.go, pkg/pooltypes/pooltypes.go, pkg/valueobject/exchange.go
=> EX-2270: integrate clipper rfq

pkg/liquidity-source/fluid/dex-t1/pool_tracker.go
=> feat: fluid dex v1 state overrides

pkg/liquidity-source/swaap-v2/pool_simulator.go, pkg/liquidity-source/swaap-v2/pool_simulator_test.go
=> chore: fix swaap update balance

pkg/liquidity-source/fluid/dex-t1/pool_tracker.go, pkg/liquidity-source/generic-simple-rate/pool_tracker.go, pkg/liquidity-source/mantle/meth/pool_list_updater.go, pkg/liquidity-source/mantle/meth/pool_tracker.go
=> Feat: state overrides simple rate meth

pkg/liquidity-source/bebop/client/http.go, pkg/liquidity-source/bebop/rfq.go
- Bebop use checksum address
- Bebop requires specifying only Sell or Buy amount
=> fix: 🩹 bebop: Checksum address & remove BuyAmounts

pkg/liquidity-source/clipper/pool_simulator.go, pkg/liquidity-source/clipper/pool_simulator_test.go
=> fix: switch clipper to accurate calculation

pkg/swaplimit/single_swap.go
- panic: new(SingleSwapLimit) -> swapped == nil
=> fix: 🩹 swaplimit: newSingle

pkg/liquidity-source/deltaswap-v1/pool_tracker.go
=> feat: deltaswap-v1 stateoverrides

pkg/liquidity-source/bebop/rfq.go, pkg/liquidity-source/clipper/rfq.go, pkg/liquidity-source/dexalot/rfq.go, pkg/liquidity-source/hashflow-v3/rfq.go, pkg/liquidity-source/native-v1/client/http.go, pkg/liquidity-source/native-v1/rfq.go, pkg/liquidity-source/native-v1/type.go, pkg/liquidity-source/swaap-v2/rfq.go, pkg/source/kyber-pmm/rfq.go, pkg/source/limitorder/rfq.go, pkg/source/pool/iface.go, pkg/source/pool/rfq.go
=> feat: implement batch RFQ

pkg/source/velodrome/pool_simulator.go, pkg/source/velodrome/pool_simulator_test.go
=> fix(velodrome) : Prevent from swapping the entire reserve in pool

pkg/source/iziswap/constant.go, pkg/source/iziswap/pool_simulator.go, pkg/source/iziswap/type.go
=> feat : add DefaultGas for Iziswap

pkg/liquidity-source/ethena/susde/pool_simulator.go, pkg/liquidity-source/ethena/susde/pool_simulator_test.go
=> fix: fix UpdateBalance function for ethena-susde

pkg/liquidity-source/uniswap-v1/pool_tracker.go
=> fix(uniswap-v1): Handle empty reserve

pkg/liquidity-source/fluid/dex-t1/abis.go, pkg/liquidity-source/fluid/dex-t1/abis/dexReservesResolver.json, pkg/liquidity-source/fluid/dex-t1/abis/storageRead.json, pkg/liquidity-source/fluid/dex-t1/constant.go, pkg/liquidity-source/fluid/dex-t1/embed.go, pkg/liquidity-source/fluid/dex-t1/pool_simulator.go, pkg/liquidity-source/fluid/dex-t1/pool_simulator_test.go, pkg/liquidity-source/fluid/dex-t1/pool_tracker.go, pkg/liquidity-source/fluid/dex-t1/pool_tracker_test.go, pkg/liquidity-source/fluid/dex-t1/types.go
=> Update(fluid-dex-t1): Adjust some logic related to the new contract update

pkg/liquidity-source/clipper/pool_simulator.go, pkg/valueobject/exchange.go
=> feat: add single swap source

pkg/liquidity-source/clipper/client/http.go
=> chore: handle quote error clipper

pkg/source/gmx/config.go, pkg/source/gmx/price_feed_reader.go, pkg/source/gmx/vault_scanner.go
=> fix(KTX): Add configuration for GMX dex-type to select correct contract function on Mantle

pkg/source/gmx/price_feed_reader.go, pkg/source/gmx/vault_scanner.go
=> fix(ktx): Correct PriceFeed's function name 

pkg/liquidity-source/fluid/dex-t1/pool_list_updater.go, pkg/liquidity-source/fluid/dex-t1/pool_simulator.go, pkg/liquidity-source/fluid/dex-t1/pool_simulator_test.go, pkg/liquidity-source/fluid/dex-t1/pool_tracker.go
=> fix(fluid-dex-t1): Correct reserve decimals before checking

pkg/liquidity-source/fluid/dex-t1/pool_tracker.go
=> fix(fluid-dex) : Update logic calculating max reserves

pkg/liquidity-source/dodo/shared/config.go, pkg/liquidity-source/dodo/shared/pool_tracker.go
=> fix(dodo-classical): Bypass non-existent fields on Ethereum contract 

pkg/source/algebrav1/pool_simulator.go, pkg/source/algebrav1/type.go, pkg/source/nuriv2/pool_simulator.go, pkg/source/nuriv2/type.go, pkg/source/pancakev3/pool_simulator.go, pkg/source/pancakev3/pool_simulator_bigint.go, pkg/source/pancakev3/type.go, pkg/source/ramsesv2/pool_simulator.go, pkg/source/ramsesv2/type.go, pkg/source/slipstream/pool_simulator.go, pkg/source/slipstream/type.go, pkg/source/solidly-v3/pool_simulator.go, pkg/source/solidly-v3/type.go, pkg/source/uniswapv3/pool_simulator.go, pkg/source/uniswapv3/pool_simulator_bigint.go, pkg/source/uniswapv3/type.go
=> add priceLimit to pool extra

pkg/liquidity-source/ringswap/pool_simulator.go, pkg/liquidity-source/ringswap/pool_simulator_test.go, pkg/liquidity-source/ringswap/types.go
=> Update(Ringswap): Add fields support expanding to ETH

pkg/liquidity-source/ringswap/constant.go, pkg/liquidity-source/ringswap/pool_tracker.go
=> Fix(ringswap): Update logic fetching token reserves

pkg/source/kyber-pmm/pool_simulator.go, pkg/swaplimit/swapped_inventory.go
=> fix: 🩹 swappedInventory: add Clone functions

pkg/liquidity-source/etherfi/eeth/constant.go, pkg/liquidity-source/etherfi/eeth/pool_tracker.go, pkg/liquidity-source/etherfi/weeth/constant.go, pkg/liquidity-source/etherfi/weeth/pool_tracker.go
=> chore: increase reserve for etherfi-eeth

pkg/liquidity-source/ringswap/pool_simulator.go, pkg/liquidity-source/ringswap/pool_simulator_test.go
=> Implement SwapLimit for Ringswap

pkg/source/kyber-pmm/constant.go, pkg/source/kyber-pmm/pool_simulator.go, pkg/source/kyber-pmm/pool_simulator_test.go, pkg/swaplimit/swapped_inventory.go, pkg/util/bignumber/bignumber.go
- should use copy of the price level for each calcAmountOut
=> fix: 🩹 kyber-pmm: remove mutating price levels

pkg/swaplimit/swapped_inventory.go
=> fix: fix swapped inventory use the correct value

pkg/liquidity-source/ringswap/pool_simulator.go
=> fix(ringswap) : Wrong condition when updating swaplimit

pkg/source/algebrav1/pool_simulator.go, pkg/source/nuriv2/pool_simulator.go, pkg/source/pancakev3/pool_simulator.go, pkg/source/pancakev3/pool_simulator_bigint.go, pkg/source/ramsesv2/pool_simulator.go, pkg/source/slipstream/pool_simulator.go, pkg/source/solidly-v3/pool_simulator.go, pkg/source/uniswapv3/pool_simulator.go, pkg/source/uniswapv3/pool_simulator_bigint.go, pkg/util/bignumber/bignumber.go
=> cap pricelimit to within min/max

pkg/valueobject/exchange.go
=> chore: add etherfi-vampire to AMM sources

pkg/source/maverickv1/errors.go, pkg/source/maverickv1/math.go, pkg/source/maverickv1/math_test.go, pkg/source/maverickv1/pool_simulator.go, pkg/source/maverickv1/pool_simulator_test.go, pkg/source/maverickv1/pool_tracker.go
- **fix: maverick-v1 reverts with error('L')**
- **refactor: optimize maverick-v1**
- **ft: implement maverickv1.CloneState**
=> ft/maverickv1 revert L

pkg/source/kyber-pmm/error.go, pkg/source/kyber-pmm/pool_simulator.go, pkg/source/kyber-pmm/pool_simulator_test.go
Implement `CalcAmountIn` for `kyber-pmm`
-
- Jira: https://team-kyber.atlassian.net/browse/TRD-734
=> Implement CalcAmountIn for kyber-pmm

pkg/source/makerpsm/vat.go
=> chore: fix function name in comment

pkg/source/gmx/price_feed_reader.go
=> chore(gmx) : add default param for PriceFeedReader

pkg/valueobject/exchange.go
=> define HorizonDexIntegral const

pkg/liquidity-source/ringswap/pool_tracker.go
=> ringswap state overwrite

pkg/liquidity-source/algebra/integral/plugin.go, pkg/liquidity-source/algebra/integral/pool_tracker.go
=> Fix(Algebra-Integral): Wrong tick's type conversion

pkg/liquidity-source/algebra/integral/ticklens.go, pkg/liquidity-source/algebra/v1/ticklens.go, pkg/source/algebrav1/ticklens.go, pkg/util/ticklens/ticklens.go
=> remove deleted ticks when fetching from ticklens

pkg/source/limitorder/pool_simulator.go, pkg/source/limitorder/pool_simulator_test.go
=> fix LO swapInfo.AmountIn in case take fee in takerAsset

pkg/liquidity-source/virtual-fun/constant.go, pkg/liquidity-source/virtual-fun/pool_list_updater.go, pkg/liquidity-source/virtual-fun/pool_simulator.go, pkg/liquidity-source/virtual-fun/pool_simulator_test.go, pkg/liquidity-source/virtual-fun/pool_tracker.go, pkg/liquidity-source/virtual-fun/types.go
=> update(virtual-fun): Adjust the estimated gas if pool triggers logic to deploy Uni pool

pkg/source/liquiditybookv20/pools_list_updater.go, pkg/source/liquiditybookv21/pools_list_updater.go, pkg/valueobject/chain.go
=> [liquidity book DEXes] Set offset as timestamp of pool for checkpoint support

pkg/valueobject/chain.go, pkg/valueobject/exchange.go
=> Add sboom exchange

pkg/liquidity-source/hashflow-v3/type.go
=> fix(hashflow-v3): fix invalid quoteTokenAmount

pkg/liquidity-source/beets-ss/abis.go, pkg/liquidity-source/beets-ss/abis/SonicStaking.json, pkg/liquidity-source/beets-ss/config.go, pkg/liquidity-source/beets-ss/constant.go, pkg/liquidity-source/beets-ss/embed.go, pkg/liquidity-source/beets-ss/pool_list_updater.go, pkg/liquidity-source/beets-ss/pool_simulator.go, pkg/liquidity-source/beets-ss/pool_simulator_test.go, pkg/liquidity-source/beets-ss/pool_tracker.go, pkg/liquidity-source/beets-ss/types.go, pkg/msgpack/register_pool_types.go, pkg/pooltypes/pooltypes.go, pkg/valueobject/chain.go, pkg/valueobject/exchange.go
=> Integrate beets-staked-sonic

pkg/liquidity-source/dodo/shared/pool_tracker.go
=> pool tracker updates

pkg/liquidity-source/curve/stable-ng/math.go, pkg/liquidity-source/deltaswap-v1/pool_simulator.go, pkg/liquidity-source/dodo/classical/sell_helper.go, pkg/liquidity-source/dodo/classical/trader.go, pkg/liquidity-source/dodo/dpp/trader.go, pkg/liquidity-source/dodo/dsp/trader.go, pkg/liquidity-source/dodo/dvm/trader.go, pkg/liquidity-source/ringswap/pool_simulator.go, pkg/liquidity-source/solidly-v2/abis.go, pkg/liquidity-source/solidly-v2/abis/Factory.json, pkg/liquidity-source/solidly-v2/abis/Pool.json, pkg/liquidity-source/solidly-v2/config.go, pkg/liquidity-source/solidly-v2/constant.go, pkg/liquidity-source/solidly-v2/embed.go, pkg/liquidity-source/solidly-v2/pool_list_updater.go, pkg/liquidity-source/solidly-v2/pool_simulator.go, pkg/liquidity-source/solidly-v2/pool_simulator_test.go, pkg/liquidity-source/solidly-v2/pool_tracker.go, pkg/liquidity-source/solidly-v2/types.go, pkg/liquidity-source/uniswap-v2/pool_simulator.go, pkg/liquidity-source/velodrome-v1/pool_simulator.go, pkg/liquidity-source/velodrome-v2/pool_simulator.go, pkg/liquidity-source/velodrome-v2/pool_tracker.go, pkg/liquidity-source/velodrome-v2/types.go, pkg/liquidity-source/virtual-fun/pool_simulator.go, pkg/msgpack/register_pool_types.go, pkg/pooltypes/pooltypes.go, pkg/valueobject/chain.go, pkg/valueobject/exchange.go
=> Integrate solidly-v2

pkg/liquidity-source/bebop/rfq.go, pkg/liquidity-source/bebop/type.go
=> [Bebop] Support aggregate order

pkg/liquidity-source/algebra/v1/constant.go, pkg/liquidity-source/algebra/v1/ticklens.go, pkg/liquidity-source/algebra/v1/type.go
Details: https://team-kyber.atlassian.net/browse/EX-2682
=> ft: update ticklens AlgebraV1

pkg/liquidity-source/lo1inch/type.go
=> refactor: add field TakerRate for 1inch Order

pkg/liquidity-source/lo1inch/helper/bytes_iter.go, pkg/liquidity-source/lo1inch/helper/extension.go, pkg/liquidity-source/lo1inch/helper/extension_test.go, pkg/liquidity-source/lo1inch/helper/helper.go, pkg/liquidity-source/lo1inch/helper/interaction.go, pkg/liquidity-source/lo1inch/helper/maker_traits.go, pkg/liquidity-source/lo1inch/helper/maker_traits_test.go, pkg/liquidity-source/lo1inch/helper/signature.go, pkg/liquidity-source/lo1inch/helper/signature_test.go, pkg/liquidity-source/lo1inch/helper/taker_traits.go, pkg/liquidity-source/lo1inch/pool_simulator.go
=> refactor: filter expired 1inch limit orders

pkg/liquidity-source/solidly-v2/constant.go, pkg/liquidity-source/swap-x-v2/abis.go, pkg/liquidity-source/swap-x-v2/abis/Factory.json, pkg/liquidity-source/swap-x-v2/abis/Pool.json, pkg/liquidity-source/swap-x-v2/config.go, pkg/liquidity-source/swap-x-v2/constant.go, pkg/liquidity-source/swap-x-v2/embed.go, pkg/liquidity-source/swap-x-v2/pool_list_updater.go, pkg/liquidity-source/swap-x-v2/pool_tracker.go, pkg/pooltypes/pooltypes.go, pkg/valueobject/chain.go
=> feat : Integrate swap-x-v2

pkg/source/maverickv1/math.go, pkg/source/maverickv1/pool_simulator.go, pkg/valueobject/chain.go
=> chore(maverick-v1): set ScaleToAmount function publicly

pkg/liquidity-source/algebra/integral/constant.go, pkg/liquidity-source/algebra/integral/ticklens.go, pkg/liquidity-source/algebra/integral/type.go
- Zap-service: override pool state for Algebra Integral
=> ft: update ticklens algebra integral

pkg/swaplimit/swapped_inventory.go, pkg/util/bignumber/bignumber.go
=> fix: skip tracking pmm swap out inventory

pkg/liquidity-source/fluid/dex-t1/constant.go, pkg/liquidity-source/fluid/dex-t1/pool_simulator_test.go
had increased the extra buffer constant number in the wrong direction :no_mouth:
=> fix(fluid-dex): fix verify reserves buffer

pkg/liquidity-source/clipper/pool_simulator.go
=> chore (clipper): add minimum amount in

pkg/liquidity-source/fluid/dex-t1/constant.go, pkg/liquidity-source/fluid/dex-t1/pool_simulator.go, pkg/valueobject/chain.go
=> fluid-dex : Add condition for amountIn

pkg/liquidity-source/algebra/integral/pool_simulator_test.go, pkg/liquidity-source/algebra/integral/pool_tracker.go, pkg/liquidity-source/curve/tricrypto-ng/pools_list_updater.go, pkg/liquidity-source/curve/twocrypto-ng/pools_list_updater.go, pkg/valueobject/chain.go
=> Fix algebra-integral test 

.github/workflows/pr-bump-go-mod.yaml
=> add zap-service to PR bump action

pkg/source/limitorder/constant.go, pkg/source/limitorder/pool_simulator.go, pkg/source/limitorder/pool_simulator_calc_amount_in.go, pkg/source/limitorder/pool_simulator_calc_amount_in_test.go, pkg/source/limitorder/pool_simulator_test.go
=> opt(lo): filter out orders with zero taking amount

pkg/liquidity-source/overnight-usdp/abis.go, pkg/liquidity-source/overnight-usdp/abis/ERC20.json, pkg/liquidity-source/overnight-usdp/abis/Exchange.json, pkg/liquidity-source/overnight-usdp/config.go, pkg/liquidity-source/overnight-usdp/constant.go, pkg/liquidity-source/overnight-usdp/embed.go, pkg/liquidity-source/overnight-usdp/pool_list_updater.go, pkg/liquidity-source/overnight-usdp/pool_simulator.go, pkg/liquidity-source/overnight-usdp/pool_simulator_test.go, pkg/liquidity-source/overnight-usdp/pool_tracker.go, pkg/liquidity-source/overnight-usdp/type.go, pkg/msgpack/register_pool_types.go, pkg/pooltypes/pooltypes.go, pkg/valueobject/chain.go, pkg/valueobject/exchange.go
=> ft: Integrate overnight-usdp

pkg/liquidity-source/kyber-pmm/rfq.go, pkg/liquidity-source/kyber-pmm/type.go
- kyberswap rfq need sender for filtering purpose
=> feat: ✨ kyber-pmm: add rfq sender

pkg/liquidity-source/kyber-pmm/rfq.go, pkg/liquidity-source/kyber-pmm/type.go
- build signature with exclusive for the kyberswap's executor
=> feat: ✨ kyber-pmm: add allowed sender

pkg/liquidity-source/algebra/integral/constant.go, pkg/liquidity-source/algebra/integral/plugin.go, pkg/liquidity-source/algebra/integral/pool_tracker.go, pkg/liquidity-source/algebra/integral/ticklens.go, pkg/liquidity-source/algebra/integral/type.go, pkg/liquidity-source/algebra/pool_tracker.go, pkg/liquidity-source/algebra/v1/constant.go, pkg/liquidity-source/algebra/v1/pool_tracker.go, pkg/liquidity-source/algebra/v1/ticklens.go, pkg/liquidity-source/algebra/v1/type.go
to maximise reusing existing data and clean up old data
=> ft: optimize algebra timepoints fetching logic

pkg/liquidity-source/solidly-v2/abis.go, pkg/liquidity-source/solidly-v2/abis/ShadowLegacy.json, pkg/liquidity-source/solidly-v2/config.go, pkg/liquidity-source/solidly-v2/constant.go, pkg/liquidity-source/solidly-v2/embed.go, pkg/liquidity-source/solidly-v2/pool_list_updater.go, pkg/liquidity-source/solidly-v2/pool_simulator.go, pkg/liquidity-source/solidly-v2/pool_tracker.go, pkg/liquidity-source/solidly-v2/types.go, pkg/valueobject/chain.go, pkg/valueobject/exchange.go
=> Update(Solidly-v2): Support shadow-legacy

pkg/liquidity-source/overnight-usdp/pool_simulator.go, pkg/liquidity-source/overnight-usdp/pool_simulator_test.go
=> fix wrong rate at overnight-usdp

pkg/liquidity-source/balancer-v3/math/log_exp_math.go, pkg/liquidity-source/balancer-v3/weighted/pool_simulator_test.go
=> balancer-v3 : fix math operation 

pkg/liquidity-source/ringswap/pool_simulator.go
Give correct logic for CanSwapFrom/To for ringswap pool simulator
=> fix: logic scan swap for ringswap

pkg/liquidity-source/uniswap-v4/config.go, pkg/liquidity-source/uniswap-v4/constant.go, pkg/liquidity-source/uniswap-v4/pool_tracker.go, pkg/liquidity-source/uniswap-v4/pool_tracker_test.go
=> univ4: support fetch tick from StateView

pkg/liquidity-source/kyber-pmm/client/error.go, pkg/liquidity-source/kyber-pmm/client/http.go, pkg/liquidity-source/kyber-pmm/rfq.go, pkg/source/pool/rfq.go
=> Update alpha fee asset

pkg/liquidity-source/velodrome-v1/pool_simulator.go, pkg/liquidity-source/velodrome-v1/pool_simulator_test.go, pkg/liquidity-source/velodrome-v2/pool_simulator.go, pkg/valueobject/exchange.go
=> ft: integrate squadswap-v2

pkg/liquidity-source/kyber-pmm/config.go, pkg/liquidity-source/kyber-pmm/rfq.go
- In trading team, we no need to validate check return maker amount with min maker amount. So this  PR add a flag to ignore it.
=> Kyber-PMM: Ignore check maker amount

go.mod, go.sum, pkg/liquidity-source/uniswap-v4/custom-hook/bunni-v2/constant.go, pkg/liquidity-source/uniswap-v4/custom-hook/bunni-v2/hub_contract.go, pkg/liquidity-source/uniswap-v4/custom-hook/bunni-v2/reserves.go, pkg/liquidity-source/uniswap-v4/pool_tracker.go
=> feat: support custom reserves fetching for bunni-v2

pkg/valueobject/exchange.go
=> EX-2542: register fake pool exchange

pkg/pooltypes/factory_test.go, pkg/pooltypes/pooltypes.go, pkg/valueobject/exchange.go
=> integrate one-bit

pkg/liquidity-source/solidly-v2/pool_list_updater.go, pkg/liquidity-source/swap-x-v2/pool_list_updater.go, pkg/liquidity-source/velodrome-v1/pool_list_updater.go, pkg/liquidity-source/velodrome-v2/pool_list_updater.go
=> chore: fix some comments

pkg/liquidity-source/erc4626/abis.go, pkg/liquidity-source/erc4626/abis/ERC4626.json, pkg/liquidity-source/erc4626/config.go, pkg/liquidity-source/erc4626/constant.go, pkg/liquidity-source/erc4626/embed.go, pkg/liquidity-source/erc4626/pool_simulator.go, pkg/liquidity-source/erc4626/pool_simulator_test.go, pkg/liquidity-source/erc4626/pool_tracker.go, pkg/liquidity-source/erc4626/pools_list_updater.go, pkg/liquidity-source/erc4626/type.go, pkg/msgpack/register_pool_types.gen.go, pkg/pooltypes/factory_test.go, pkg/pooltypes/pooltypes.go, pkg/valueobject/exchange.go
=> feat: integrate erc4626/beefy-sonic

pkg/liquidity-source/balancer-v2/stable/pool_simulator.go
=> balancer-v2: fix logic getBasePool

pkg/liquidity-source/fluid/dex-t1/abis/dexReservesResolver.json, pkg/source/wombat/pool_tracker.go
=> fix(fluid-dex): fix wrong abi methods

pkg/liquidity-source/uniswap-v4/pool_tracker.go
=> fix: fix panic division zero when calculating uniswap-v4 reserves

pkg/liquidity-source/woofi-v21/abi/Cloracle.json, pkg/liquidity-source/woofi-v21/abi/ERC20.json, pkg/liquidity-source/woofi-v21/abi/IntegrationHelper.json, pkg/liquidity-source/woofi-v21/abi/WooPPV2_1.json, pkg/liquidity-source/woofi-v21/abi/WooracleV2_2_1.json, pkg/liquidity-source/woofi-v21/constant.go, pkg/liquidity-source/woofi-v21/pool_simulator.go, pkg/liquidity-source/woofi-v21/pool_simulator_test.go, pkg/liquidity-source/woofi-v21/pool_tracker.go, pkg/liquidity-source/woofi-v21/pools_list_updater.go, pkg/liquidity-source/woofi-v21/type.go
=> fix some woofi-v3 potential errors

pkg/liquidity-source/woofi-v21/pool_simulator.go
=> fix concurrent RW issue on woofi-v3

pkg/liquidity-source/woofi-v21/pool_simulator.go
=> woofi-v3: shallow copy states

pkg/entity/token.go
=> Add simplified token entity

pkg/liquidity-source/woofi-v21/constant.go, pkg/liquidity-source/woofi-v21/pool_simulator.go
=> fix(woofi-v3): ORACLE_FEASIBLE error

pkg/entity/token.go
=> Add method GetAddress to token and simplfiedToken

pkg/entity/pool.go, pkg/liquidity-source/ambient/types.go
There is a [new function](https://pkg.go.dev/slices@go1.21.0#Contains) added in the go1.21 standard library, which can make the code more concise and easy to read.
=> refactor: use slices.Contains to simplify code

pkg/liquidity-source/mkr-sky/pool_tracker.go
=> fix mkr-sky tracker

pkg/liquidity-source/balancer-v2/composable-stable/abis/ComposableStablePool.json, pkg/liquidity-source/balancer-v2/composable-stable/constant.go, pkg/liquidity-source/balancer-v2/composable-stable/pool_tracker.go, pkg/liquidity-source/balancer-v2/composable-stable/type.go
=> fix error log on balancer-composable-stable-v2

pkg/entity/pool.go, pkg/liquidity-source/native/v3/constant.go, pkg/liquidity-source/native/v3/pool_simulator.go, pkg/liquidity-source/native/v3/pool_tracker.go, pkg/liquidity-source/native/v3/pools_list_updater.go, pkg/liquidity-source/native/v3/type.go
=> Fix no pools created on native-v3 arbitrum

pkg/liquidity-source/maverick-v2/pool_tracker_test.go
=> fix: integration test maverick-v2 

pkg/liquidity-source/maverick/v2/pool_tracker.go
=> fix: maverick v2 overrides logic

pkg/liquidity-source/euler-swap/pool_tracker.go, pkg/liquidity-source/uniswap-v4/hooks/euler/abis.go, pkg/liquidity-source/uniswap-v4/hooks/euler/abis/EVault.json, pkg/liquidity-source/uniswap-v4/hooks/euler/abis/EulerSwap.json, pkg/liquidity-source/uniswap-v4/hooks/euler/abis/EulerSwapFactory.json, pkg/liquidity-source/uniswap-v4/hooks/euler/config.go, pkg/liquidity-source/uniswap-v4/hooks/euler/constant.go, pkg/liquidity-source/uniswap-v4/hooks/euler/embed.go, pkg/liquidity-source/uniswap-v4/hooks/euler/math.go, pkg/liquidity-source/uniswap-v4/hooks/euler/pool_list_updater.go, pkg/liquidity-source/uniswap-v4/hooks/euler/pool_list_updater_test.go, pkg/liquidity-source/uniswap-v4/hooks/euler/pool_simulator.go, pkg/liquidity-source/uniswap-v4/hooks/euler/pool_simulator_test.go, pkg/liquidity-source/uniswap-v4/hooks/euler/pool_tracker.go, pkg/liquidity-source/uniswap-v4/hooks/euler/types.go, pkg/msgpack/register_pool_types.gen.go, pkg/pooltypes/pooltypes.go, pkg/valueobject/exchange.go
=> Integrate uniswap-v4-euler (hook)

pkg/liquidity-source/uniswap-lo/pool_simulator.go
=> Fix: uniswaplo approval address

pkg/liquidity-source/euler-swap/pool_tracker.go
=> euler: block pools which all vaults have zero balance

pkg/liquidity-source/aave-v3/pool_list_updater_test.go, pkg/liquidity-source/aave-v3/pool_tracker.go, pkg/liquidity-source/aave-v3/types.go
=> fix(aave-v3): empty pool extra

pkg/liquidity-source/aave-v3/types.go, pkg/liquidity-source/native/v1/type_test.go
=> aave-v3: correct json tag

pkg/liquidity-source/bebop/rfq.go, pkg/liquidity-source/clipper/rfq.go, pkg/liquidity-source/dexalot/rfq.go, pkg/liquidity-source/native/v1/rfq.go, pkg/liquidity-source/swaap-v2/rfq.go, pkg/source/pool/rfq.go
=> Assign origin instead of sender in Firm request 

pkg/liquidity-source/integral/abis/TwapOracle.json, pkg/liquidity-source/integral/abis/TwapRelayer.json, pkg/liquidity-source/integral/pool_tracker.go
=> fix(integral): checking isPairEnabled didn't work as expected

pkg/liquidity-source/euler-swap/constant.go, pkg/liquidity-source/euler-swap/pool_simulator.go, pkg/liquidity-source/euler-swap/pool_simulator_test.go, pkg/liquidity-source/euler-swap/pool_tracker.go, pkg/liquidity-source/euler-swap/types.go
=> Fix(euler-swap): Add swap limitation check

pkg/liquidity-source/balancer-v2/stable/pool_tracker.go, pkg/liquidity-source/balancer-v2/weighted/pool_tracker.go
=> fix(balancer-v2): Fallback to zero when failing to fetch invariant

pkg/liquidity-source/uniswap-lo/constant.go, pkg/liquidity-source/uniswap-lo/pool_simulator.go, pkg/liquidity-source/uniswap-lo/pool_simulator_test.go
=> feat: add ChainID field to StaticExtra and PoolSimulator

pkg/liquidity-source/uniswap-v4/hooks/zora-v4/constant.go, pkg/liquidity-source/uniswap-v4/hooks/zora-v4/hook.go, pkg/msgpack/register_pool_types.gen.go, pkg/valueobject/exchange.go
=> feat: integrate zora-v4 hook

pkg/liquidity-source/uniswap-v4/hooks/clanker/hook_test.go, pkg/liquidity-source/uniswap-v4/pool_simulator.go
=> Fix(uni-v4): unsafe modification of amountIn

pkg/liquidity-source/uniswap-v4/hooks/zora-v4/constant.go, pkg/liquidity-source/uniswap-v4/hooks/zora/constant.go, pkg/liquidity-source/uniswap-v4/hooks/zora/hook.go, pkg/liquidity-source/velodrome-v1/fee_tracker.go, pkg/msgpack/register_pool_types.gen.go
=> feat: update zora new hooks

pkg/liquidity-source/brownfi/pool_list_updater.go, pkg/liquidity-source/curve/llamma/pool_tracker.go, pkg/liquidity-source/integral/pool_list_updater_test.go, pkg/liquidity-source/nomiswap/pools_list_updater.go, pkg/liquidity-source/pancake-infinity/bin/pool_simulator_test.go, pkg/liquidity-source/pancake-infinity/cl/pool_simulator_test.go, pkg/liquidity-source/woofi-v2/pool_simulator.go, pkg/liquidity-source/woofi-v21/pool_simulator.go
Inspired by https://github.com/KyberNetwork/kyberswap-dex-lib/pull/815  and replace all.
=> refactor: use the built-in max/min to simplify the code

pkg/liquidity-source/arena-bc/pool_tracker.go, pkg/liquidity-source/arena-bc/types.go
// TODO: implement logic to delete pool
=> chore: skip state update for deployed tokens

pkg/liquidity-source/euler-swap/pool_simulator.go
=> use LTV from destination vault to calculate new collateral value

pkg/liquidity-source/uniswap/v4/hooks/bunni-v2/legacy_hook.go, pkg/liquidity-source/uniswap/v4/hooks/bunni-v2/static_config.go, pkg/liquidity-source/uniswap/v4/hooks/bunni-v2/tracker.go, pkg/liquidity-source/uniswap/v4/hooks/clanker/dynamic_fee_hook.go, pkg/liquidity-source/uniswap/v4/hooks/clanker/errors.go, pkg/liquidity-source/uniswap/v4/hooks/clanker/static_fee_hook.go
=> chore : disable legacy bunni-v2 pools

pkg/liquidity-source/uniswap/v4/hooks/bunni-v2/static_config.go
=> chore(bunni-v2): LDF deployment addresses in bunni-v2 docs is wrong

pkg/valueobject/exchange.go
=> Integrate kittenswap-v2

pkg/liquidity-source/renzo/ezeth/constant.go, pkg/liquidity-source/renzo/ezeth/pool_list_updater.go, pkg/liquidity-source/renzo/ezeth/pool_simulator.go, pkg/liquidity-source/renzo/ezeth/pool_simulator_test.go, pkg/liquidity-source/renzo/ezeth/types.go
=> Update implementation of renzo-ezeth

pkg/liquidity-source/balancer/v3/eclp/pool_simulator_test.go, pkg/liquidity-source/balancer/v3/shared/buffer_math.go, pkg/liquidity-source/balancer/v3/shared/constant.go, pkg/liquidity-source/balancer/v3/shared/pool_tracker.go, pkg/liquidity-source/balancer/v3/shared/type.go, pkg/liquidity-source/balancer/v3/stable/pool_simulator_test.go, pkg/liquidity-source/balancer/v3/weighted/pool_simulator_test.go, pkg/liquidity-source/erc4626/constant.go, pkg/liquidity-source/erc4626/helper.go, pkg/liquidity-source/erc4626/pool_simulator.go, pkg/liquidity-source/erc4626/pool_simulator_test.go, pkg/liquidity-source/erc4626/pool_tracker.go, pkg/liquidity-source/erc4626/type.go, pkg/valueobject/exchange.go
=> Improve(erc4626) : prefetch rate at multiple amounts

pkg/liquidity-source/fluid/dex-lite/pool_simulator.go, pkg/liquidity-source/integral/pool_simulator.go
=> fix bugs on fluid-dex-lite & integral

pkg/liquidity-source/euler-swap/abis/EVault.json, pkg/liquidity-source/euler-swap/abis/EthereumVaultConnector.json, pkg/liquidity-source/euler-swap/abis/EulerRouter.json, pkg/liquidity-source/euler-swap/abis/EulerSwap.json, pkg/liquidity-source/euler-swap/abis/EulerSwapFactory.json, pkg/liquidity-source/euler-swap/constant.go, pkg/liquidity-source/euler-swap/math.go, pkg/liquidity-source/euler-swap/pool_list_updater.go, pkg/liquidity-source/euler-swap/pool_simulator.go, pkg/liquidity-source/euler-swap/pool_simulator_test.go, pkg/liquidity-source/euler-swap/pool_tracker.go, pkg/liquidity-source/euler-swap/types.go, pkg/util/big256/big256.go
=> fix(euler-swap): only track account's liquidity through controller

pkg/liquidity-source/euler-swap/constant.go, pkg/liquidity-source/euler-swap/pool_simulator.go, pkg/liquidity-source/euler-swap/pool_simulator_test.go, pkg/liquidity-source/euler-swap/pool_tracker.go, pkg/liquidity-source/euler-swap/types.go
=> fix some eulerswap missmatch logic

pkg/liquidity-source/miro-migrator/abis.go, pkg/liquidity-source/miro-migrator/abis/MiroMigrator.json, pkg/liquidity-source/miro-migrator/config.go, pkg/liquidity-source/miro-migrator/constant.go, pkg/liquidity-source/miro-migrator/embed.go, pkg/liquidity-source/miro-migrator/pool_list_updater.go, pkg/liquidity-source/miro-migrator/pool_simulator.go, pkg/liquidity-source/miro-migrator/pool_tracker.go, pkg/liquidity-source/miro-migrator/types.go, pkg/msgpack/register_pool_types.gen.go, pkg/pooltypes/pooltypes.go, pkg/valueobject/exchange.go
=> Integrate miro-migrator

pkg/liquidity-source/curve/twocrypto-ng/constant.go, pkg/liquidity-source/curve/twocrypto-ng/curve_twocrypto_optimized.go, pkg/liquidity-source/curve/twocrypto-ng/math.go, pkg/liquidity-source/curve/twocrypto-ng/math_test.go, pkg/liquidity-source/curve/twocrypto-ng/pool_simulator_test.go, pkg/liquidity-source/curve/twocrypto-ng/pool_tracker.go, pkg/liquidity-source/curve/twocrypto-ng/type.go
=> Update (curve twocrypto-ng): Port appropriate math lib from YB's pools
